( "ढांचे" nil ( Dh A an c e ))
( "खराब" nil ( Kh r A b ))
( "प्रदेश" nil ( p _ r d e S ))
( "फोन" nil ( ph o n ))
( "प्रति" nil ( p _ r t i ))
( "पुनर्विचार" nil ( p u n r _ v i c A r ))
( "प्रशासन" nil ( p _ r S A s n ))
( "हैं" nil ( h E an ))
( "हैः" nil ( h E ah ))
( "है।" nil ( h E _ ))
( "गुप्त" nil ( g u p _ t ))
( "बाह्य" nil ( b A h _ y ))
( "सामाजिक" nil ( s A m A j i k ))
( "सोचता" nil ( s o c t A ))
( "सोचते" nil ( s o c t e ))
( "कमाई" nil ( k m A I ))
( "साधन" nil ( s A dh n ))
( "आभास" nil ( A bh A s ))
( "आर्थिक" nil ( A r _ th i k ))
( "समिति" nil ( s m i t i ))
( "किराया" nil ( k i r A y A ))
( "किराये" nil ( k i r A y e ))
( "स्वास्ठ्य" nil ( s _ v A s _ Th _ y ))
( "लेना" nil ( l e n A ))
( "लेने" nil ( l e n e ))
( "सिस्टम" nil ( s i s _ T m ))
( "जायेंगे" nil ( j A y e an g e ))
( "पद" nil ( p  d ))
( "पर" nil ( p  r ))
( "पा" nil ( p  A ))
( "पी" nil ( p  I ))
( "पे" nil ( p  e ))
( "पढ़" nil ( p  Rh ))
( "सूचना" nil ( s U c n A ))
( "खाना" nil ( Kh A n A ))
( "खाने" nil ( Kh A n e ))
( "हवा" nil ( h v A ))
( "निर्यात" nil ( n i r _ y A t ))
( "गिरफ्तार" nil ( g i r ph _ t A r ))
( "सुनवाई" nil ( s u n v A I ))
( "गईं" nil ( g I an ))
( "मैं" nil ( m E an ))
( "दुम" nil ( d u m ))
( "सवारी" nil ( s v A r I ))
( "कार्यालय" nil ( k A r _ y A l y ))
( "तरफ" nil ( t r ph ))
( "तरह" nil ( t r h ))
( "प्रचलित" nil ( p _ r c l i t ))
( "कौशल" nil ( k au S l ))
( "कौंसिल" nil ( k au an s i ))
( "नहीं" nil ( n h I an ))
( "शक्ति" nil ( S k _ t i ))
( "गलत" nil ( g l t ))
( "आडवाणी" nil ( A D v A N I ))
( "किसी" nil ( k i s I ))
( "नैतिक" nil ( n E t i k ))
( "अथवा" nil ( a th v A ))
( "रिपोर्ट" nil ( r i p o r _ T ))
( "गए" nil ( g  e ))
( "लीजिए" nil ( l I j i e ))
( "सांस्कृतिक" nil ( s A an s _ k ri t i k ))
( "प्रकार" nil ( p _ r k A r ))
( "प्रारम्भ" nil ( p _ r A r m _ bh ))
( "जायेगा" nil ( j A y e g A ))
( "रसायनिक" nil ( r s A y n i k ))
( "कोई" nil ( k o I ))
( "फिल्में" nil ( ph i _ m e an ))
( "सतर्कता" nil ( s t r _ k t A ))
( "हम:" nil ( h  m ))
( "विशेश" nil ( v i S e S ))
( "विशेष" nil ( v i S e S ))
( "है'" nil ( h  E ))
( "है," nil ( h  E ))
( "है." nil ( h  E ))
( "है:" nil ( h  E ))
( "है?" nil ( h  E ))
( "हो'" nil ( h  o ))
( "हो," nil ( h  o ))
( "हो." nil ( h  o ))
( "इसलिए" nil ( i s l i e ))
( "देशों" nil ( d e S o an ))
( "कुशल" nil ( k u S l ))
( "कपद्द" nil ( k p d _ d ))
( "तेल" nil ( t e l ))
( "सफ़ेद" nil ( s f e d ))
( "जीव" nil ( j I v ))
( "सोचना" nil ( s o c n A ))
( "इस्लाम" nil ( i s _ l A m ))
( "प्रवेश" nil ( p _ r v e S ))
( "पहलुओं" nil ( p h l u o an ))
( "दोनों" nil ( d o n o an ))
( "पुरानी" nil ( p u r A n I ))
( "आवेदन" nil ( A v e d n ))
( "कच्चा" nil ( k c _ c A ))
( "पड़ता" nil ( p R t A ))
( "उतरने" nil ( u t r n e ))
( "इंग्लैंड" nil ( i an g _ l E an D ))
( "परिणाम" nil ( p r i N A m ))
( "उग्रवादी" nil ( u g _ r v A d I ))
( "पांव," nil ( p A an v ))
( "प्रबन्ध" nil ( p _ r b n _ dh ))
( "विराम" nil ( v i r A m ))
( "इसमें" nil ( i s m e an ))
( "प्रकट" nil ( p _ r k T ))
( "मा" nil ( m  A ))
( "मै" nil ( m  E ))
( "मतभेद" nil ( m t bh e d ))
( "बातचीत" nil ( b A t c I t ))
( "ध्वनि" nil ( dh _ v n i ))
( "अकेले" nil ( a k e l e ))
( "उन्हें" nil ( u n _ h e an ))
( "जाएगी" nil ( j A e g I ))
( "खेले" nil ( Kh e l e ))
( "संचार" nil ( s an c A r ))
( "एक-दूसरे" nil ( e k d U s r e ))
( "कार्यकाल" nil ( k A r _ y k A l ))
( "सरकारी" nil ( s r k A r I ))
( "सीमेंट" nil ( s I m e an T ))
( "स्रोत" nil ( s _ r o t ))
( "स'ख्या" nil ( s Kh _ y A ))
( "संकेत" nil ( s an k e t ))
( "अगर" nil ( a g r ))
( "नवजात" nil ( n v j A t ))
( "छह" nil ( ch  h ))
( "बहुत" nil ( b h u t ))
( "वैज्ञानिक" nil ( v E j _ ny A n i k ))
( "द'ह'ग" nil ( d h g ))
( "आरंभ" nil ( A r an bh ))
( "जिसका" nil ( j i s k A ))
( "दबाव" nil ( d b A v ))
( "सामांय" nil ( s A m A an y ))
( "बद्द" nil ( b d _ d ))
( "बद्र" nil ( b d _ r ))
( "पक़्स-ई" nil ( p kh _ s I ))
( "बना" nil ( b n A ))
( "फिल्मों" nil ( ph i _ m o an ))
( "खनिज" nil ( Kh n i j ))
( "संरक्षण" nil ( s an r k _ S N ))
( "समृद्धि" nil ( s m ri d _ dh i ))
( "चाहिए?" nil ( c A h i e ))
( "दृष्टि" nil ( d ri S _ T i ))
( "मुज़्ह" nil ( m u z _ h ))
( "आक्रमन्द" nil ( A k _ r m n _ d ))
( "केरल" nil ( k e r l ))
( "संस्कार" nil ( s an s _ k A r ))
( "राजनीतिक" nil ( r A j n I t i k ))
( "हेतु" nil ( h e t u ))
( "पुन" nil ( p u n ))
( "दर्ज" nil ( d r _ j ))
( "सात" nil ( s A t ))
( "साथ" nil ( s A th ))
( "सार" nil ( s A r ))
( "साफ़" nil ( s A f ))
( "नरम" nil ( n r m ))
( "उपकरन्द" nil ( u p k r n _ d ))
( "समाप्त" nil ( s m A p _ t ))
( "मदद" nil ( m d d ))
( "घोषित" nil ( Gh o S i t ))
( "मुफ्त" nil ( m u ph _ t ))
( "विचार" nil ( v i c A r ))
( "सेवा" nil ( s e v A ))
( "शामिल" nil ( S A m i ))
( "लय" nil ( l  y ))
( "ली" nil ( l  I ))
( "लो" nil ( l  o ))
( "ऋतु" nil ( ri t u ))
( "पुत्र" nil ( p u t _ r ))
( "संभवत:" nil ( s an bh v t ))
( "अभिजात" nil ( a bh i j A t ))
( "यथा" nil ( y th A ))
( "मार्ग" nil ( m A r _ g ))
( "ढोरों" nil ( Dh o r o an ))
( "लागू" nil ( l A g U ))
( "पीछे" nil ( p I ch e ))
( "जहां" nil ( j h A an ))
( "जहाज" nil ( j h A j ))
( "जहाज़" nil ( j h A z ))
( "वाजपेयी" nil ( v A j p e y I ))
( "विषय" nil ( v i S y ))
( "ः" nil ( ah ))
( "आ" nil ( A ))
( "ई" nil ( I ))
( "ए" nil ( e ))
( "ऐ" nil ( E ))
( "ओ" nil ( o ))
( "क" nil ( k ))
( "ग" nil ( g ))
( "घ" nil ( Gh ))
( "छ" nil ( ch ))
( "त" nil ( t ))
( "द" nil ( d ))
( "न" nil ( n ))
( "ब" nil ( b ))
( "ल" nil ( l ))
( "व" nil ( v ))
( "ह" nil ( h ))
( "।" nil ( _ ))
( "सकता" nil ( s k t A ))
( "सकती" nil ( s k t I ))
( "सकते" nil ( s k t e ))
( "नशीली" nil ( n S I l I ))
( "सुबह" nil ( s u b h ))
( "लिखा" nil ( l i Kh A ))
( "भाग" nil ( bh A g ))
( "भाव" nil ( bh A v ))
( "बंद" nil ( b an d ))
( "आंशिक" nil ( A an S i k ))
( "टी" nil ( T  I ))
( "दिशा" nil ( d i S A ))
( "छात्र" nil ( ch A t _ r ))
( "ठीक" nil ( Th I k ))
( "अन्य" nil ( a n _ y ))
( "व्हेल" nil ( v _ h e l ))
( "क्रिया" nil ( k _ r i y A ))
( "एकमात्र" nil ( e k m A t _ r ))
( "तथा" nil ( t th A ))
( "सम्मिलित" nil ( s m _ m i i t ))
( "वाद-विवाद" nil ( v A d v i v A d ))
( "पवित्र" nil ( p v i t _ r ))
( "दातों" nil ( d A t o an ))
( "बद्द~ई" nil ( b d _ d I ))
( "पढ़ाई" nil ( p Rh A I ))
( "गंभीर" nil ( g an bh I r ))
( "जरूरत" nil ( j r U r t ))
( "वितरण" nil ( v i t r N ))
( "चलाया" nil ( c l A y A ))
( "पुरस्कार" nil ( p u r s _ k A r ))
( "सूअरों" nil ( s U a r o an ))
( "टेलिफोन" nil ( T e l i ph o n ))
( "उत्तराधिकारी" nil ( u t _ t r A dh i k A r I ))
( "अवसर" nil ( a v s r ))
( "उतना" nil ( u t n A ))
( "जैन" nil ( j E n ))
( "पीले" nil ( p I l e ))
( "तुम्हे" nil ( t u m _ h e ))
( "शिमला" nil ( S i m l A ))
( "बिना" nil ( b i n A ))
( "अलग" nil ( a l g ))
( "पीड़ा" nil ( p I R A ))
( "शव" nil ( S  v ))
( "हैन'." nil ( h E n ))
( "हुआ" nil ( h u A ))
( "हुई" nil ( h u I ))
( "हुए" nil ( h u e ))
( "प्रजनन" nil ( p _ r j n n ))
( "नियुक्ति" nil ( n i y u k _ t i ))
( "संचालन" nil ( s an c A l n ))
( "कहते" nil ( k h t e ))
( "करेंगे" nil ( k r e an g e ))
( "नस्ल" nil ( n s _ l ))
( "द्द" nil ( d _ d ))
( "देखते" nil ( d e Kh t e ))
( "पूरा" nil ( p U r A ))
( "पैदा" nil ( p E d A ))
( "ज्यादा" nil ( j _ y A d A ))
( "आवाज" nil ( A v A j ))
( "आवाज़" nil ( A v A z ))
( "प्रेस" nil ( p _ r e s ))
( "देगा" nil ( d e g A ))
( "स्तर." nil ( s _ t r ))
( "नियंत्रण" nil ( n i y an t _ r N ))
( "मगर" nil ( m g r ))
( "गाद" nil ( g A d ))
( "खोलने" nil ( Kh o l n e ))
( "अंडमान" nil ( a an D m A n ))
( "भूल" nil ( bh U l ))
( "कभी" nil ( k bh I ))
( "चाहेंगे" nil ( c A h e an g e ))
( "अटल" nil ( a T l ))
( "लोगो'" nil ( l o g o ))
( "हैं." nil ( h E an ))
( "हैं:" nil ( h E an ))
( "हैं?" nil ( h E an ))
( "हैन'" nil ( h E n ))
( "निष्पक्ष" nil ( n i S _ p k _ S ))
( "होता" nil ( h o t A ))
( "होती" nil ( h o t I ))
( "होते" nil ( h o t e ))
( "खबर" nil ( Kh b r ))
( "संतोष" nil ( s an t o S ))
( "संपत्ति" nil ( s an p t _ t i ))
( "आयुक्त" nil ( A y u k _ t ))
( "काला" nil ( k A l A ))
( "मूर्ति" nil ( m U r _ t i ))
( "पटल" nil ( p T l ))
( "पद्द" nil ( p d _ d ))
( "पद्र" nil ( p d _ r ))
( "बनावट" nil ( b n A v T ))
( "मशीनरी" nil ( m S I n r I ))
( "आचरण" nil ( A c r N ))
( "आवश्यक" nil ( A v S _ y k ))
( "अधिक" nil ( a dh i k ))
( "नियम" nil ( n i y m ))
( "निम्नलिखित" nil ( n i m _ n l i Kh i t ))
( "समूची" nil ( s m U c I ))
( "लालच" nil ( l A l c ))
( "परिस्थितियां" nil ( p r i s _ th i t i y A an ))
( "तंत्र" nil ( t an t _ r ))
( "सच्चा" nil ( s c _ c A ))
( "अनाज" nil ( a n A j ))
( "मानते" nil ( m A n t e ))
( "शायद" nil ( S A y d ))
( "समारोह" nil ( s m A r o h ))
( "वस्त्र" nil ( v s _ t _ r ))
( "प्रमोद" nil ( p _ r m o d ))
( "कहान'" nil ( k h A n ))
( "पिता" nil ( p i t A ))
( "कोयला" nil ( k o y l A ))
( "कोयले" nil ( k o y l e ))
( "रंग" nil ( r an g ))
( "ध्यान" nil ( dh _ y A n ))
( "कहना" nil ( k h n A ))
( "पुरुष" nil ( p u r u S ))
( "संबंध" nil ( s an b an dh ))
( "निजी" nil ( n i j I ))
( "देखना" nil ( d e Kh n A ))
( "बेच" nil ( b e c ))
( "तीन" nil ( t I n ))
( "विभागों" nil ( v i bh A g o an ))
( "विषयों" nil ( v i S y o an ))
( "सकारात्मक" nil ( s k A r A t _ m k ))
( "पशु" nil ( p S u ))
( "निर्धारण" nil ( n i r _ dh A r N ))
( "अधिकारियों" nil ( a dh i k A r i y o an ))
( "सर्वेक्षण" nil ( s r _ v e k _ S N ))
( "करनेवाला" nil ( k r n e v A l A ))
( "बढ़ती" nil ( b Rh t I ))
( "ड्रग्स" nil ( D _ r g _ s ))
( "समाप्ति" nil ( s m A p _ t i ))
( "लकद्द~ई" nil ( l k d _ d I ))
( "संसद" nil ( s an s d ))
( "आधारभूत" nil ( A dh A r bh U t ))
( "धूम्रपान" nil ( dh U m _ r p A n ))
( "कार्यपालिका" nil ( k A r _ y p A l i k A ))
( "विद्वान" nil ( v i d _ v A n ))
( "कितने" nil ( k i t n e ))
( "विलम्ब" nil ( v i m _ b ))
( "यानी" nil ( y A n I ))
( "तथ्य" nil ( t th _ y ))
( "पुलिस" nil ( p u l i s ))
( "बार-बार" nil ( b A r b A r ))
( "गुलाब" nil ( g u l A b ))
( "कलकत्ता" nil ( k l k t _ t A ))
( "ताकतों" nil ( t A k t o an ))
( "होना" nil ( h o n A ))
( "होनी" nil ( h o n I ))
( "होने" nil ( h o n e ))
( "दात" nil ( d A t ))
( "दाम" nil ( d A m ))
( "ईंधन" nil ( I an dh n ))
( "बोलना" nil ( b o l n A ))
( "``समारोह" nil ( s m A r o h ))
( "गाँव" nil ( g A l v ))
( "नहीन'" nil ( n h I n ))
( "गया" nil ( g y A ))
( "गयी" nil ( g y I ))
( "गये" nil ( g y e ))
( "सहायता" nil ( s h A y t A ))
( "मुस्लिम" nil ( m u s _ l i m ))
( "जानता" nil ( j A n t A ))
( "जानते" nil ( j A n t e ))
( "और" nil ( au  r ))
( "'मेरा" nil ( m e r A ))
( "निश्चित" nil ( n i S _ c i t ))
( "उनका" nil ( u n k A ))
( "मिलेंगे" nil ( m i e an g e ))
( "उनके" nil ( u n k e ))
( "विभाग" nil ( v i bh A g ))
( "न्यायालय" nil ( n _ y A y A l y ))
( "इतनी" nil ( i t n I ))
( "इतने" nil ( i t n e ))
( "नीला" nil ( n I l A ))
( "वापिस" nil ( v A p i s ))
( "सफेद" nil ( s ph e d ))
( "मानने" nil ( m A n n e ))
( "सामान्यत:" nil ( s A m A n _ y t ))
( "बडे" nil ( b D e ))
( "पहला" nil ( p h l A ))
( "पहली" nil ( p h l I ))
( "पहलू" nil ( p h l U ))
( "पहले" nil ( p h l e ))
( "विकसित" nil ( v i k s i t ))
( "राज्य" nil ( r A j _ y ))
( "लगा" nil ( l g A ))
( "लगी" nil ( l g I ))
( "मध्य" nil ( m dh _ y ))
( "प्रथम" nil ( p _ r th m ))
( "प्रत्यक्ष" nil ( p _ r t _ y k _ S ))
( "प्रयोजनों" nil ( p _ r y o j n o an ))
( "अदालत" nil ( a d A l t ))
( "खेल" nil ( Kh e l ))
( "जिससे" nil ( j i s s e ))
( "प्रयुक्त" nil ( p _ r y u k _ t ))
( "भाषा" nil ( bh A S A ))
( "केंद्रीय" nil ( k e an d _ r I y ))
( "बोस" nil ( b o s ))
( "चाहे" nil ( c A h e ))
( "घोड़ों" nil ( Gh o R o an ))
( "अक्सर" nil ( a k _ s r ))
( "विवरन्द" nil ( v i v r n _ d ))
( "जरुरतों" nil ( j r u r t o an ))
( "मौलिक" nil ( m au l i k ))
( "दूसरा" nil ( d U s r A ))
( "दूसरी" nil ( d U s r I ))
( "दूसरे" nil ( d U s r e ))
( "अपील" nil ( a p I l ))
( "सो," nil ( s  o ))
( "अधिकारिता" nil ( a dh i k A r i t A ))
( "व्यावहारिक" nil ( v _ y A v h A r i k ))
( "मशीनों" nil ( m S I n o an ))
( "सदस्य" nil ( s d s _ y ))
( "चूंकि" nil ( c U an k i ))
( "शिकायत" nil ( S i k A y t ))
( "इसी" nil ( i s I ))
( "इसे" nil ( i s e ))
( "यन्त्र" nil ( y n _ t _ r ))
( "या," nil ( y  A ))
( "रहता" nil ( r h t A ))
( "रहती" nil ( r h t I ))
( "रहते" nil ( r h t e ))
( "फल" nil ( ph  l ))
( "स्तर" nil ( s _ t r ))
( "हैपेटाईटिस" nil ( h E p e T A I T i s ))
( "जलवायु" nil ( j l v A y u ))
( "शुरू" nil ( S u r U ))
( "दी." nil ( d  I ))
( "दी?" nil ( d  I ))
( "य'त्र" nil ( y t _ r ))
( "क्षेत्रों" nil ( k _ S e t _ r o an ))
( "लेकिन" nil ( l e k i n ))
( "दूध" nil ( d U dh ))
( "दूर" nil ( d U r ))
( "व्यर्थ" nil ( v _ y r _ th ))
( "आदत" nil ( A d t ))
( "आदि" nil ( A d i ))
( "रक्त" nil ( r k _ t ))
( "महासचिव" nil ( m h A s c i v ))
( "मतदाताओं" nil ( m t d A t A o an ))
( "अनुकूल" nil ( a n u k U l ))
( "खिलाड़ी" nil ( Kh i A R I ))
( "और:" nil ( au  r ))
( "सॉल्वैंट" nil ( s E l _ v E an T ))
( "बेहतर" nil ( b e h t r ))
( "परन्तु" nil ( p r n _ t u ))
( "जानना" nil ( j A n n A ))
( "चाहता" nil ( c A h t A ))
( "चाहते" nil ( c A h t e ))
( "वाद" nil ( v A d ))
( "फायदा" nil ( ph A y d A ))
( "यहूदी" nil ( y h U d I ))
( "घट" nil ( Gh  T ))
( "घर" nil ( Gh  r ))
( "बहाव" nil ( b h A v ))
( "रेत" nil ( r e t ))
( "गायन" nil ( g A y n ))
( "रेस" nil ( r e s ))
( "सकें" nil ( s k e an ))
( ".कानूनी" nil ( k A n U n I ))
( "मोत'आ" nil ( m o t A ))
( "अर्थ" nil ( a r _ th ))
( "सूती" nil ( s U t I ))
( "प्रादेशिक" nil ( p _ r A d e S i k ))
( "कौन" nil ( k au n ))
( "जगह" nil ( j g h ))
( "कांग्रेस" nil ( k A an g _ r e s ))
( "पदार्थ" nil ( p d A r _ th ))
( "छूट" nil ( ch U T ))
( "छूत" nil ( ch U t ))
( "चिकित्सा" nil ( c i k i t _ s A ))
( "बढने" nil ( b Dh n e ))
( "शहीद" nil ( S h I d ))
( "चलाने" nil ( c l A n e ))
( "स्कूलों" nil ( s _ k U l o an ))
( "खोज" nil ( Kh o j ))
( "मंत्री" nil ( m an t _ r I ))
( "मेरा" nil ( m e r A ))
( "मेरी" nil ( m e r I ))
( "मेरे" nil ( m e r e ))
( "ताकि" nil ( t A k i ))
( "अत" nil ( a  t ))
( "अब" nil ( a  b ))
( "पार" nil ( p A r ))
( "पास" nil ( p A s ))
( "चरण" nil ( c r N ))
( "ऊपरी" nil ( U p r I ))
( "घंटे" nil ( Gh an T e ))
( "स्वार्थ" nil ( s _ v A r _ th ))
( "शपथ" nil ( S p th ))
( "सिर्फ" nil ( s i r _ ph ))
( "कत'हिन" nil ( k t h i n ))
( "आघात" nil ( A Gh A t ))
( "कहा" nil ( k h A ))
( "है..." nil ( h  E ))
( "रहना" nil ( r h n A ))
( "रहने" nil ( r h n e ))
( "यह" nil ( y  h ))
( "या" nil ( y  A ))
( "यू" nil ( y  U ))
( "ये" nil ( y  e ))
( "शक्तिशाली" nil ( S k _ t i S A l I ))
( "प्राय:" nil ( p _ r A y ))
( "जनमत" nil ( j n m t ))
( "कमरा" nil ( k m r A ))
( "कमरे" nil ( k m r e ))
( "समीक्षा" nil ( s m I k _ S A ))
( "संतुष्ट" nil ( s an t u S _ T ))
( "ब्राह्मण" nil ( b _ r A h _ m N ))
( "हालत" nil ( h A l t ))
( "स्थानीय" nil ( s _ th A n I y ))
( "उत्साह" nil ( u t _ s A h ))
( "किस्म" nil ( k i s _ m ))
( "बाहर" nil ( b A h r ))
( "शैक्षणिक" nil ( S E k _ S N i k ))
( "टिकट" nil ( T i k T ))
( "फूलो'" nil ( ph U l o ))
( "जब" nil ( j  b ))
( "जल" nil ( j  l ))
( "जा" nil ( j  A ))
( "जी" nil ( j  I ))
( "जो" nil ( j  o ))
( "वर्षा" nil ( v r _ S A ))
( "पेद्द" nil ( p e d _ d ))
( "रोग" nil ( r o g ))
( "जटिल" nil ( j T i ))
( "शराब" nil ( S r A b ))
( "बल्कि" nil ( b l _ k i ))
( "राजस्थान" nil ( r A j s _ th A n ))
( "ठाकरे" nil ( Th A k r e ))
( "चीनी" nil ( c I n I ))
( "कुत्ते" nil ( k u t _ t e ))
( "आगे" nil ( A g e ))
( "संक्रामक" nil ( s an k _ r A m k ))
( "बोतल" nil ( b o t l ))
( "काफी" nil ( k A ph I ))
( "द्वारा" nil ( d _ v A r A ))
( "सुनना" nil ( s u n n A ))
( "सुनने" nil ( s u n n e ))
( "सरकार" nil ( s r k A r ))
( "राजस्व" nil ( r A j s _ v ))
( "रक्षा" nil ( r k _ S A ))
( "प्रभावित" nil ( p _ r bh A v i t ))
( "यही" nil ( y h I ))
( "मिलता" nil ( m i t A ))
( "मिलती" nil ( m i t I ))
( "मिलते" nil ( m i t e ))
( "स्वास्थ्य" nil ( s _ v A s _ th _ y ))
( "तौर" nil ( t au r ))
( "उत" nil ( u  t ))
( "उन" nil ( u  n ))
( "उस" nil ( u  s ))
( "दीर्घकालिक" nil ( d I r _ Gh k A l i k ))
( "मुंबई" nil ( m u an b I ))
( "सिर" nil ( s i r ))
( "चाहिए" nil ( c A h i e ))
( "समुद्र" nil ( s m u d _ r ))
( "विद्या" nil ( v i d _ y A ))
( "निम्न" nil ( n i m _ n ))
( "परीक्षण" nil ( p r I k _ S N ))
( "दूरी" nil ( d U r I ))
( "व्यापारिक" nil ( v _ y A p A r i k ))
( "अनुभवी" nil ( a n u bh v I ))
( "धन्यवाद" nil ( dh n _ y v A d ))
( "छ:" nil ( ch ))
( "हां" nil ( h A an ))
( "हाथ" nil ( h A th ))
( "वृद्धि" nil ( v ri d _ dh i ))
( "संघ" nil ( s an Gh ))
( "तकनीकी" nil ( t k n I k I ))
( "यदि" nil ( y d i ))
( "वाहन" nil ( v A h n ))
( "सोवियत" nil ( s o v i y t ))
( "निकट" nil ( n i k T ))
( "बीच" nil ( b I c ))
( "आज़्ख" nil ( A z _ Kh ))
( "प्रबंधन``." nil ( p _ r b an dh n ))
( "हमने" nil ( h m n e ))
( "समस्याओं" nil ( s m s _ y A o an ))
( "अनुसूचित" nil ( a n u s U c i t ))
( "उद्द" nil ( u d _ d ))
( "लंबे" nil ( l an b e ))
( "निकालना" nil ( n i k A l n A ))
( "विद्युत" nil ( v i d _ y u t ))
( "दिखाई" nil ( d i Kh A I ))
( "ऊंचाई" nil ( U an c A I ))
( "बोर्ड" nil ( b o r _ D ))
( "वादा" nil ( v A d A ))
( "ज़रुरतों" nil ( z r u r t o an ))
( "नामों" nil ( n A m o an ))
( "घत'" nil ( Gh  t ))
( "माँ" nil ( m A l ))
( "माप" nil ( m A p ))
( "मार" nil ( m A r ))
( "माल" nil ( m A l ))
( "मास" nil ( m A s ))
( "सामान" nil ( s A m A n ))
( "प्रक्रिया" nil ( p _ r k _ r i y A ))
( "कायम" nil ( k A y m ))
( "पसंद" nil ( p s an d ))
( "बजाने" nil ( b j A n e ))
( "एव'" nil ( e  v ))
( "पूर्न्द" nil ( p U r _ n _ d ))
( "बदलाव" nil ( b d l A v ))
( "स्वाधीनता" nil ( s _ v A dh I n t A ))
( "केवल" nil ( k e v l ))
( "जॉन" nil ( j E n ))
( "स्कूल" nil ( s _ k U l ))
( "अपराध" nil ( a p r A dh ))
( "पाकिस्तान" nil ( p A k i s _ t A n ))
( "ऊपर" nil ( U p r ))
( "छोटे" nil ( ch o T e ))
( "क्षतिपूर्ति" nil ( k _ S t i p U r _ t i ))
( "कुछ" nil ( k u ch ))
( "सकती?" nil ( s k t I ))
( "अनुच्छेद" nil ( a n u c _ ch e d ))
( "हूँ" nil ( h U l ))
( "बच्चों" nil ( b c _ c o an ))
( "जनजाति" nil ( j n j A t i ))
( "वाद्यों" nil ( v A d _ y o an ))
( "योग्यता" nil ( y o g _ y t A ))
( "आपने" nil ( A p n e ))
( "मुख्य" nil ( m u Kh _ y ))
( "बधाई" nil ( b dh A I ))
( "शिक्षा" nil ( S i k _ S A ))
( "संस्थान" nil ( s an s _ th A n ))
( "भारत" nil ( bh A r t ))
( "भारी" nil ( bh A r I ))
( "संस्करण" nil ( s an s _ k r N ))
( "चालू" nil ( c A l U ))
( "प्राथमिक" nil ( p _ r A th m i k ))
( "सरल" nil ( s r l ))
( "अफसोस" nil ( a ph s o s ))
( "संकल्पना" nil ( s an k l _ p n A ))
( "गिर" nil ( g i r ))
( "छोड़कर" nil ( ch o R k r ))
( "बहरहाल" nil ( b h r h A l ))
( "व्र्क्ष्क़्स" nil ( v _ r _ k _ S _ kh _ s ))
( "कमर" nil ( k m r ))
( "कमी" nil ( k m I ))
( "लालकृष्ण" nil ( l A l k ri S _ N ))
( "तक" nil ( t  k ))
( "तट" nil ( t  T ))
( "तब" nil ( t  b ))
( "तय" nil ( t  y ))
( "तो" nil ( t  o ))
( "मनुष्य" nil ( m n u S _ y ))
( "स्वायत्तता" nil ( s _ v A y t _ t t A ))
( "आपका" nil ( A p k A ))
( "आपकी" nil ( A p k I ))
( "आपके" nil ( A p k e ))
( "आपको" nil ( A p k o ))
( "वापस" nil ( v A p s ))
( "खुली" nil ( Kh u l I ))
( "युवा" nil ( y u v A ))
( "मूल्य" nil ( m U l _ y ))
( "जन्म" nil ( j n _ m ))
( "रखा" nil ( r Kh A ))
( "रखे" nil ( r Kh e ))
( "मकान" nil ( m k A n ))
( "नमूना" nil ( n m U n A ))
( "उदार" nil ( u d A r ))
( "भरे" nil ( bh r e ))
( "अगले" nil ( a g l e ))
( "नृत्य" nil ( n ri t _ y ))
( "जलने" nil ( j l n e ))
( "हैं।" nil ( h E an _ ))
( "कानूनी," nil ( k A n U n I ))
( "क्या" nil ( k _ y A ))
( "प्रकत'" nil ( p _ r k t ))
( "तुरही" nil ( t u r h I ))
( "गाने" nil ( g A n e ))
( "नही" nil ( n h I ))
( "माता-पिता" nil ( m A t A p i t A ))
( "मृत्यु" nil ( m ri t _ y u ))
( "तुमने" nil ( t u m n e ))
( "गर्भपात" nil ( g r _ bh p A t ))
( "संयंत्र" nil ( s an y an t _ r ))
( "कैसा" nil ( k E s A ))
( "कैसे" nil ( k E s e ))
( "चाहें" nil ( c A h e an ))
( "चिंतित" nil ( c i an t i t ))
( "व्यवस्था" nil ( v _ y v s _ th A ))
( "विरुद्ध" nil ( v i r u d _ dh ))
( "चेहरे" nil ( c e h r e ))
( "चाहिये" nil ( c A h i y e ))
( "स्वतंत्र" nil ( s _ v t an t _ r ))
( "प्रयोग" nil ( p _ r y o g ))
( "तुम" nil ( t u m ))
( "लाभ" nil ( l A bh ))
( "लाल" nil ( l A l ))
( "साथी" nil ( s A th I ))
( "क़्स-एत्र" nil ( kh _ s e t _ r ))
( "विवादों" nil ( v i v A d o an ))
( "जाँच" nil ( j A l c ))
( "नदी" nil ( n d I ))
( "अंतिम" nil ( a an t i m ))
( "तुमको" nil ( t u m k o ))
( "गृह" nil ( g ri h ))
( "थीं" nil ( th I an ))
( "बहरहाल," nil ( b h r h A l ))
( "अवज्ञा" nil ( a v j _ ny A ))
( "अतः" nil ( a t ah ))
( "नई" nil ( n  I ))
( "नए" nil ( n  e ))
( "ना" nil ( n  A ))
( "ने" nil ( n  e ))
( "रहेगा" nil ( r h e g A ))
( "दशकों" nil ( d S k o an ))
( "घूस" nil ( Gh U s ))
( "आश्चर्य" nil ( A S _ c r _ y ))
( "दिए" nil ( d i e ))
( "दिन" nil ( d i n ))
( "दिल" nil ( d  i ))
( "दाेनाें" nil ( d A e n A e an ))
( "समितियों" nil ( s m i t i y o an ))
( "आकस्मिक" nil ( A k s _ m i k ))
( "उत्तेजना" nil ( u t _ t e j n A ))
( "विहार" nil ( v i h A r ))
( "मे'" nil ( m  e ))
( "मामला" nil ( m A m l A ))
( "पता" nil ( p t A ))
( "पति" nil ( p t i ))
( "बिल्कुल" nil ( b i _ k u l ))
( "बढावा" nil ( b Dh A v A ))
( "गांव" nil ( g A an v ))
( "शब्दों" nil ( S b _ d o an ))
( "थे." nil ( th  e ))
( "स'ब'धी" nil ( s b dh I ))
( "गरम" nil ( g r m ))
( "दंड" nil ( d an D ))
( "दंत" nil ( d an t ))
( "सामाजिक," nil ( s A m A j i k ))
( "साज़्प" nil ( s A z _ p ))
( "कई" nil ( k  I ))
( "कत" nil ( k  t ))
( "कब" nil ( k  b ))
( "कम" nil ( k  m ))
( "कर" nil ( k  r ))
( "कल" nil ( k  l ))
( "कह" nil ( k  h ))
( "का" nil ( k  A ))
( "कि" nil ( k  i ))
( "की" nil ( k  I ))
( "कॆ" nil ( k  e ))
( "के" nil ( k  e ))
( "को" nil ( k  o ))
( "आमदनी" nil ( A m d n I ))
( "चीज" nil ( c I j ))
( "चीन" nil ( c I n ))
( "चीज़" nil ( c I z ))
( "आकार" nil ( A k A r ))
( "भूरे" nil ( bh U r e ))
( "हमें" nil ( h m e an ))
( "चलता" nil ( c l t A ))
( "चलते" nil ( c l t e ))
( "ऊआ." nil ( U  A ))
( "ऊई." nil ( U  I ))
( "बिहार" nil ( b i h A r ))
( "हूँ?" nil ( h U l ))
( "त'उकद्द~आ" nil ( t u k d _ d A ))
( "हून'" nil ( h U n ))
( "तुम्हें" nil ( t u m _ h e an ))
( "यद्यपि" nil ( y d _ y p i ))
( "बिजली" nil ( b i j l I ))
( "श्रम" nil ( S _ r m ))
( "श्री" nil ( S _ r I ))
( "उत्तेजित" nil ( u t _ t e j i t ))
( "वक्ष" nil ( v k _ S ))
( "मन्द" nil ( m n _ d ))
( "जान" nil ( j A n ))
( "पीना" nil ( p I n A ))
( "लूट" nil ( l U T ))
( "प्रबंध" nil ( p _ r b an dh ))
( "सौदा" nil ( s au d A ))
( "शिकार" nil ( S i k A r ))
( "अभ्यास" nil ( a bh _ y A s ))
( "कराने" nil ( k r A n e ))
( "बज" nil ( b  j ))
( "बम" nil ( b  m ))
( "बी" nil ( b  I ))
( "बढ़" nil ( b  Rh ))
( "स्थल" nil ( s _ th l ))
( "परंतु" nil ( p r an t u ))
( "उपकरण" nil ( u p k r N ))
( "प्रस्तुत" nil ( p _ r s _ t u t ))
( "जाये" nil ( j A y e ))
( "कीजिए" nil ( k I j i e ))
( "वाला" nil ( v A l A ))
( "वाली" nil ( v A l I ))
( "वाले" nil ( v A l e ))
( "भरने" nil ( bh r n e ))
( "सीधी" nil ( s I dh I ))
( "सीधे" nil ( s I dh e ))
( "परिस्थिति" nil ( p r i s _ th i t i ))
( "शिशुओं" nil ( S i S u o an ))
( "लोहा" nil ( l o h A ))
( "लोहे" nil ( l o h e ))
( "असफल" nil ( a s ph l ))
( "धर्म" nil ( dh r _ m ))
( "कसौटी" nil ( k s au T I ))
( "घाटी" nil ( Gh A T I ))
( "सहायक" nil ( s h A y k ))
( "उम्र" nil ( u m _ r ))
( "पेद्द~" nil ( p e d _ d ))
( "अकी" nil ( a k I ))
( "अके" nil ( a k e ))
( "जिसमे'" nil ( j i s m e ))
( "कार्यवाही" nil ( k A r _ y v A h I ))
( "सीमित" nil ( s I m i t ))
( "ढोर" nil ( Dh o r ))
( "ढोल" nil ( Dh o l ))
( "खिलाफ" nil ( Kh i A ph ))
( "उसने" nil ( u s n e ))
( "डॉक्टर" nil ( D E k _ T r ))
( "चलने" nil ( c l n e ))
( "वालों" nil ( v A l o an ))
( "शाम" nil ( S A m ))
( "शासन" nil ( S A s n ))
( "उपलब्ध" nil ( u p l b _ dh ))
( "चीजों" nil ( c I j o an ))
( "अधिकार" nil ( a dh i k A r ))
( "आंखें" nil ( A an Kh e an ))
( "डाली" nil ( D A l I ))
( "पतला" nil ( p t l A ))
( "पतले" nil ( p t l e ))
( "अंत" nil ( a an t ))
( "अंय" nil ( a an y ))
( "जूँ" nil ( j U l ))
( "जूट" nil ( j U T ))
( "प्रत्येक" nil ( p _ r t _ y e k ))
( "आई" nil ( A  I ))
( "आज" nil ( A  j ))
( "आठ" nil ( A  Th ))
( "आन" nil ( A  n ))
( "आप" nil ( A  p ))
( "आम" nil ( A  m ))
( "आर" nil ( A  r ))
( "देते" nil ( d e t e ))
( "उसका" nil ( u s k A ))
( "उसकी" nil ( u s k I ))
( "उसके" nil ( u s k e ))
( "नागरिक" nil ( n A g r i k ))
( "नियमित" nil ( n i y m i t ))
( "नमक" nil ( n m k ))
( "अलग-अलग" nil ( a l g a l g ))
( "विदेशी" nil ( v i d e S I ))
( "सभापति" nil ( s bh A p t i ))
( "मैरी" nil ( m E r I ))
( "तेजी" nil ( t e j I ))
( "शिक़्स-आ" nil ( S i kh _ s A ))
( "प्रमुख" nil ( p _ r m u Kh ))
( "निर्धारित" nil ( n i r _ dh A r i t ))
( "सबसे" nil ( s b s e ))
( "जानकार" nil ( j A n k A r ))
( "पक्ष" nil ( p k _ S ))
( "बयान" nil ( b y A n ))
( "धातु" nil ( dh A t u ))
( "दें" nil ( d e an ))
( "देर" nil ( d e r ))
( "देश" nil ( d e S ))
( "अनुरूप" nil ( a n u r U p ))
( "किन्तु" nil ( k i n _ t u ))
( "खींच" nil ( Kh I an c ))
( "अमेरिका" nil ( a m e r i k A ))
( "होंगे?" nil ( h o an g e ))
( "सवाल" nil ( s v A l ))
( "औद्योगिक" nil ( au d _ y o g i k ))
( "वित्तीय" nil ( v i t _ t I y ))
( "भेद'" nil ( bh e d ))
( "प्रौद्योगिकी" nil ( p _ r au d _ y o g i k I ))
( "तरीकों" nil ( t r I k o an ))
( "परिस्थितियों" nil ( p r i s _ th i t i y o an ))
( "जैसे" nil ( j E s e ))
( "पालक" nil ( p A l k ))
( "पालन" nil ( p A l n ))
( "ईश्वर" nil ( I S _ v r ))
( "योजना" nil ( y o j n A ))
( "परंपरागत" nil ( p r an p r A g t ))
( "साथ-साथ" nil ( s A th s A th ))
( "छेद" nil ( ch e d ))
( "वर्षों" nil ( v r _ S o an ))
( "गर्दन" nil ( g r _ d n ))
( "बाधा" nil ( b A dh A ))
( "भेजा" nil ( bh e j A ))
( "भेजी" nil ( bh e j I ))
( "धार्मिक" nil ( dh A r _ m i k ))
( "भिन्न" nil ( bh i n _ n ))
( "ऊआ" nil ( U  A ))
( "ऊत" nil ( U  t ))
( "आवेदनपत्र" nil ( A v e d n p t _ r ))
( "महत्व" nil ( m h t _ v ))
( "प्राधिकरण" nil ( p _ r A dh i k r N ))
( "देना" nil ( d e n A ))
( "देने" nil ( d e n e ))
( "कर्तव्यों" nil ( k r _ t v _ y o an ))
( "सीख" nil ( s I Kh ))
( "रहा" nil ( r h A ))
( "रही" nil ( r h I ))
( "रहे" nil ( r h e ))
( "गाडी" nil ( g A D I ))
( "अंदर" nil ( a an d r ))
( "सूखा" nil ( s U Kh A ))
( "अत:" nil ( a  t ))
( "संपर्क" nil ( s an p r _ k ))
( "सामने" nil ( s A m n e ))
( "कान" nil ( k A n ))
( "काम" nil ( k A m ))
( "कार" nil ( k A r ))
( "काे" nil ( k A e ))
( "पहने" nil ( p h n e ))
( "अरब" nil ( a r b ))
( "केलिए" nil ( k e l i e ))
( "फूल" nil ( ph U l ))
( "खाली" nil ( Kh A l I ))
( "हिन" nil ( h i n ))
( "विकलांग" nil ( v i k l A an g ))
( "विश्वास" nil ( v i S _ v A s ))
( "ऐतिहासिक" nil ( E t i h A s i k ))
( "चुकी" nil ( c u k I ))
( "संख्या" nil ( s an Kh _ y A ))
( "आयु" nil ( A y u ))
( "बुक" nil ( b u k ))
( "तैयार" nil ( t E y A r ))
( "जळी" nil ( j l I ))
( "परत" nil ( p r t ))
( "सभा" nil ( s bh A ))
( "सभी" nil ( s bh I ))
( "पासवान" nil ( p A s v A n ))
( "दूरसंचार" nil ( d U r s an c A r ))
( "दूरभाष" nil ( d U r bh A S ))
( "उच्चतम" nil ( u c _ c t m ))
( "एवं" nil ( e v an ))
( "पत्र" nil ( p t _ r ))
( "बीमारी" nil ( b I m A r I ))
( "स्टेटमैंट" nil ( s _ T e T m E an T ))
( "लेंगे" nil ( l e an g e ))
( "डर" nil ( D  r ))
( "डा" nil ( D  A ))
( "डी" nil ( D  I ))
( "डॉ" nil ( D  E ))
( "जीवन" nil ( j I v n ))
( "हमारी" nil ( h m A r I ))
( "हमारे" nil ( h m A r e ))
( "प्रदर्शित" nil ( p _ r d r _ S i t ))
( "जाता" nil ( j A t A ))
( "जाति" nil ( j A t i ))
( "जितनी" nil ( j i t n I ))
( "जाते" nil ( j A t e ))
( "नारियल" nil ( n A r i y l ))
( "अनुभव" nil ( a n u bh v ))
( "क्यों" nil ( k _ y o an ))
( "कारण" nil ( k A r N ))
( "हमेशा" nil ( h m e S A ))
( "छोड" nil ( ch o D ))
( "छोत" nil ( ch o t ))
( "छोड़" nil ( ch o R ))
( "सेवाओं" nil ( s e v A o an ))
( "बचपन" nil ( b c p n ))
( "संयुक्त" nil ( s an y u k _ t ))
( "याद" nil ( y A d ))
( "जिसमें" nil ( j i s m e an ))
( "प्रारंभिक" nil ( p _ r A r an bh i k ))
( "दिनों" nil ( d i n o an ))
( "उंहोंने" nil ( u an h o an n e ))
( "किया" nil ( k i y A ))
( "किये" nil ( k i y e ))
( "घोद्द~ए" nil ( Gh o d _ d e ))
( "मिला" nil ( m i A ))
( "ट्रिब्यूनल" nil ( T _ r i b _ y U n l ))
( "रहा." nil ( r h A ))
( "रहे?" nil ( r h e ))
( "पेड़" nil ( p e R ))
( "भट्टाचार्य" nil ( bh T _ T A c A r _ y ))
( "प्राप्त" nil ( p _ r A p _ t ))
( "कानून" nil ( k A n U n ))
( "रानी" nil ( r A n I ))
( "मानसून" nil ( m A n s U n ))
( "कीमत" nil ( k I m t ))
( "लिया" nil ( l i y A ))
( "लिये" nil ( l i y e ))
( "किनारा" nil ( k i n A r A ))
( "इसका" nil ( i s k A ))
( "इसकी" nil ( i s k I ))
( "इसके" nil ( i s k e ))
( "इसको" nil ( i s k o ))
( "अस्तित्व" nil ( a s _ t i t _ v ))
( "बजने" nil ( b j n e ))
( "जंगलों" nil ( j an g l o an ))
( "सन" nil ( s  n ))
( "सब" nil ( s  b ))
( "सा" nil ( s  A ))
( "सी" nil ( s  I ))
( "से" nil ( s  e ))
( "सो" nil ( s  o ))
( "सूँघने" nil ( s U l Gh n e ))
( "राजनैतिक" nil ( r A j n E t i k ))
( "राज्यों" nil ( r A j _ y o an ))
( "खुद" nil ( Kh u d ))
( "अवधि" nil ( a v dh i ))
( "अवधी" nil ( a v dh I ))
( "सफ़ाई" nil ( s f A I ))
( "स्थान" nil ( s _ th A n ))
( "स्तंभ" nil ( s _ t an bh ))
( "स्पष्ट" nil ( s _ p S _ T ))
( "मैन'" nil ( m E n ))
( "उन्नत" nil ( u n _ n t ))
( "जिंदगी" nil ( j i an d g I ))
( "ंयायालय" nil ( an y A y A l y ))
( "गीत" nil ( g I t ))
( "खर्चे" nil ( Kh r _ c e ))
( "भयानक" nil ( bh y A n k ))
( "कया" nil ( k y A ))
( "क्योन'" nil ( k _ y o n ))
( "सेना" nil ( s e n A ))
( "पिछले" nil ( p i ch l e ))
( "था" nil ( th  A ))
( "थी" nil ( th  I ))
( "थे" nil ( th  e ))
( "भोजन" nil ( bh o j n ))
( "उपबंध" nil ( u p b an dh ))
( "हरा" nil ( h r A ))
( "समाज" nil ( s m A j ))
( "समान" nil ( s m A n ))
( "जनता" nil ( j n t A ))
( "इत्यादि" nil ( i t _ y A d i ))
( "जाना" nil ( j A n A ))
( "जाने" nil ( j A n e ))
( "आंदोलन" nil ( A an d o l n ))
( "तुम्हारे" nil ( t u m _ h A r e ))
( "ऐसा" nil ( E s A ))
( "ऐसी" nil ( E s I ))
( "ऐसे" nil ( E s e ))
( "अनुसार" nil ( a n u s A r ))
( "मुझे" nil ( m u jh e ))
( "पहुंच" nil ( p h u an c ))
( "पत्थर" nil ( p t _ th r ))
( "हानि" nil ( h A n i ))
( "साम्राज्य" nil ( s A m _ r A j _ y ))
( "चर्म" nil ( c r _ m ))
( "पक़्स" nil ( p kh _ s ))
( "बड़ी" nil ( b R I ))
( "बड़े" nil ( b R e ))
( "काफ़ी" nil ( k A f I ))
( "व्यापार" nil ( v _ y A p A r ))
( "तत'" nil ( t  t ))
( "शीघ्र" nil ( S I Gh _ r ))
( "देरी" nil ( d e r I ))
( "सैर" nil ( s E r ))
( "रुख" nil ( r u Kh ))
( "रुप" nil ( r u p ))
( "कार्य" nil ( k A r _ y ))
( "उन्होंने" nil ( u n _ h o an n e ))
( "तरीके" nil ( t r I k e ))
( "करता" nil ( k r t A ))
( "करती" nil ( k r t I ))
( "करते" nil ( k r t e ))
( "यंत्र" nil ( y an t _ r ))
( "असर" nil ( a s r ))
( "दिल्ली" nil ( d i _ l I ))
( "माता" nil ( m A t A ))
( "स्वर" nil ( s _ v r ))
( "ज़रुरत" nil ( z r u r t ))
( "चश्मा" nil ( c S _ m A ))
( "अपनाया" nil ( a p n A y A ))
( "दायित्व" nil ( d A y i t _ v ))
( "धारा" nil ( dh A r A ))
( "संसाधन" nil ( s an s A dh n ))
( "स'गीत" nil ( s g I t ))
( "हुआ." nil ( h u A ))
( "संयंत्रों" nil ( s an y an t _ r o an ))
( "आंध्र" nil ( A an dh _ r ))
( "लिए" nil ( l i e ))
( "हिमाचल" nil ( h i m A c l ))
( "जांच" nil ( j A an c ))
( "बातें" nil ( b A t e an ))
( "भारतीय" nil ( bh A r t I y ))
( "कर्तव्य" nil ( k r _ t v _ y ))
( "वित्त" nil ( v i t _ t ))
( "माज़्स" nil ( m A z _ s ))
( "लखनऊ" nil ( l Kh n U ))
( "संकल्प" nil ( s an k l _ p ))
( "समूह" nil ( s m U h ))
( "प्रस्ताव" nil ( p _ r s _ t A v ))
( "भाजपा" nil ( bh A j p A ))
( "समझौता" nil ( s m jh au t A ))
( "समझौते" nil ( s m jh au t e ))
( "धीमी" nil ( dh I m I ))
( "पंजाब" nil ( p an j A b ))
( "विकास" nil ( v i k A s ))
( "में" nil ( m e an ))
( "मेज़" nil ( m e z ))
( "अफ्रीका" nil ( a ph _ r I k A ))
( "आते" nil ( A t e ))
( "बावजूद" nil ( b A v j U d ))
( "उदाहरण" nil ( u d A h r N ))
( "लोगों" nil ( l o g o an ))
( "फैला" nil ( ph E l A ))
( "पाँच" nil ( p A l c ))
( "न्र्क्ष्त्य" nil ( n _ r _ k _ S _ t _ y ))
( "गिरावट." nil ( g i r A v T ))
( "पात्र" nil ( p A t _ r ))
( "व्यक्तियों" nil ( v _ y k _ t i y o an ))
( "जल्दी," nil ( j l _ d I ))
( "नाम" nil ( n A m ))
( "नाव" nil ( n A v ))
( "बेहद" nil ( b e h d ))
( "होगा" nil ( h o g A ))
( "होगी" nil ( h o g I ))
( "दृश्य" nil ( d ri S _ y ))
( "करना" nil ( k r n A ))
( "करनी" nil ( k r n I ))
( "करने" nil ( k r n e ))
( "फिल्म" nil ( ph i _ m ))
( "उपस्थित" nil ( u p s _ th i t ))
( "लद्द" nil ( l d _ d ))
( "लद्र" nil ( l d _ r ))
( "मानव" nil ( m A n v ))
( "माना" nil ( m A n A ))
( "करवाने" nil ( k r v A n e ))
( "सोना" nil ( s o n A ))
( "सोने" nil ( s o n e ))
( "संगीत" nil ( s an g I t ))
( "बनाने" nil ( b n A n e ))
( "तुम्हेन'" nil ( t u m _ h e n ))
( "सलाह" nil ( s l A h ))
( "नस्लें" nil ( n s _ l e an ))
( "पक्का" nil ( p k _ k A ))
( "उक्त" nil ( u k _ t ))
( "जिन" nil ( j i n ))
( "जिस" nil ( j i s ))
( "विभिन्न" nil ( v i bh i n _ n ))
( "क्र्क्ष्पया" nil ( k _ r _ k _ S _ p y A ))
( "बुरी" nil ( b u r I ))
( "गाद्द~ई" nil ( g A d _ d I ))
( "प्राथमिकता" nil ( p _ r A th m i k t A ))
( "सहज" nil ( s h j ))
( "सही" nil ( s h I ))
( "बातों" nil ( b A t o an ))
( "बर्फ़" nil ( b r _ f ))
( "गवाह" nil ( g v A h ))
( "प्रसारण" nil ( p _ r s A r N ))
( "खाद्य" nil ( Kh A d _ y ))
( "करके" nil ( k r k e ))
( "अतिरिक्त" nil ( a t i r i k _ t ))
( "प्रमाण" nil ( p _ r m A N ))
( "भय" nil ( bh  y ))
( "भी" nil ( bh  I ))
( "जारी" nil ( j A r I ))
( "मोल" nil ( m o l ))
( "चित्र" nil ( c i t _ r ))
( "भेंट" nil ( bh e an T ))
( "इलाज" nil ( i l A j ))
( "कल्याण" nil ( k l _ y A N ))
( "आना" nil ( A n A ))
( "आने" nil ( A n e ))
( "पूर्व" nil ( p U r _ v ))
( "धब्बे" nil ( dh b _ b e ))
( "सागर" nil ( s A g r ))
( "चुनौती" nil ( c u n au t I ))
( "क्षेत्र" nil ( k _ S e t _ r ))
( "बलों" nil ( b l o an ))
( "बिहारी" nil ( b i h A r I ))
( "सदा" nil ( s d A ))
( "लगाने" nil ( l g A n e ))
( "उसे" nil ( u s e ))
( "व्यय" nil ( v _ y y ))
( "शृंखला" nil ( S ri an Kh l A ))
( "मतदान" nil ( m t d A n ))
( "सहारा" nil ( s h A r A ))
( "प्रबंधन" nil ( p _ r b an dh n ))
( "पश्चिम" nil ( p S _ c i m ))
( "चल" nil ( c  l ))
( "वैसे" nil ( v E s e ))
( "छोत'आ" nil ( ch o t A ))
( "छोत'ई" nil ( ch o t I ))
( "छोत'ए" nil ( ch o t e ))
( "इंतजार" nil ( i an t j A r ))
( "अत्यंत" nil ( a t _ y an t ))
( "राष्ट्र" nil ( r A S _ T _ r ))
( "माननीय" nil ( m A n n I y ))
( "चाहेंगे:" nil ( c A h e an g e ))
( "सॉल्वैंट्स" nil ( s E l _ v E an T _ s ))
( "वर्ग" nil ( v r _ g ))
( "ने." nil ( n  e ))
( "सेनाओं" nil ( s e n A o an ))
( "सहयोग" nil ( s h y o g ))
( "संदर्भ" nil ( s an d r _ bh ))
( "रोज़गार" nil ( r o z g A r ))
( "इत" nil ( i  t ))
( "लेख" nil ( l e Kh ))
( "इन" nil ( i  n ))
( "इस" nil ( i  s ))
( "वाद्य" nil ( v A d _ y ))
( "पीठ" nil ( p I Th ))
( "चला" nil ( c l A ))
( "नये" nil ( n y e ))
( "कार्यकारी" nil ( k A r _ y k A r I ))
( "गुलाबी" nil ( g u l A b I ))
( "शादी" nil ( S A d I ))
( "जायेगी?" nil ( j A y e g I ))
( "अभी" nil ( a bh I ))
( "फिर" nil ( ph i r ))
( "विधानसभा" nil ( v i dh A n s bh A ))
( "मात्रा" nil ( m A t _ r A ))
( "पद्धति" nil ( p d _ dh t i ))
( "सुधार" nil ( s u dh A r ))
( "स्वरूप" nil ( s _ v r U p ))
( "चुनाव" nil ( c u n A v ))
( "हालांकि" nil ( h A l A an k i ))
( "संभवत" nil ( s an bh v t ))
( "नहीन'." nil ( n h I n ))
( "उत्तर" nil ( u t _ t r ))
( "चलचित्र" nil ( c l c i t _ r ))
( "रखना" nil ( r Kh n A ))
( "रखने" nil ( r Kh n e ))
( "जोड़ी" nil ( j o R I ))
( "बात" nil ( b A t ))
( "बाद" nil ( b A d ))
( "बार" nil ( b A r ))
( "बाल" nil ( b A l ))
( "इससे" nil ( i s s e ))
( "चिंतन" nil ( c i an t n ))
( "चिंता" nil ( c i an t A ))
( "तथाकथित" nil ( t th A k th i t ))
( "उद्योग" nil ( u d _ y o g ))
( "जोरदार" nil ( j o r d A r ))
( "देखभाल" nil ( d e Kh bh A l ))
( "कपद्द~आ" nil ( k p d _ d A ))
( "उदाहरणार्थ" nil ( u d A h r N A r _ th ))
( "बजट:" nil ( b j T ))
( "स्थिति" nil ( s _ th i t i ))
( "मात्र" nil ( m A t _ r ))
( "कर्मचारियों" nil ( k r _ m c A r i y o an ))
( "शरीर" nil ( S r I r ))
( "जरुरत" nil ( j r u r t ))
( "कारगिल" nil ( k A r g i ))
( "ईसाई" nil ( I s A I ))
( "आपूर्ति" nil ( A p U r _ t i ))
( "इनमें" nil ( i n m e an ))
( "पहचान" nil ( p h c A n ))
( "पैसा" nil ( p E s A ))
( "पैसे" nil ( p E s e ))
( "दिमाग" nil ( d i m A g ))
( "जेब" nil ( j e b ))
( "इस्पात" nil ( i s _ p A t ))
( "ऋण" nil ( ri  N ))
( "लोग" nil ( l o g ))
( "मेहनत" nil ( m e h n t ))
( "ऊनी" nil ( U n I ))
( "कानूनी" nil ( k A n U n I ))
( "वनस्पति" nil ( v n s _ p t i ))
( "इस्लामी" nil ( i s _ l A m I ))
( "बच्चा" nil ( b c _ c A ))
( "बच्चे" nil ( b c _ c e ))
( "पुष्टि" nil ( p u S _ T i ))
( "जोशी" nil ( j o S I ))
( "किए" nil ( k i e ))
( "किस" nil ( k i s ))
( "व्यापक" nil ( v _ y A p k ))
( "प्रश्न" nil ( p _ r S _ n ))
( "नौका" nil ( n au k A ))
( "आयोजित" nil ( A y o j i t ))
( "प्रतीक्षा" nil ( p _ r t I k _ S A ))
( "वर" nil ( v  r ))
( "वह" nil ( v  h ))
( "वी" nil ( v  I ))
( "वे" nil ( v  e ))
( "मजबूत" nil ( m j b U t ))
( "हीक" nil ( h I k ))
( "प्रणाली" nil ( p _ r N A l I ))
( "कार्यक्रम" nil ( k A r _ y k _ r m ))
( "समुद्री" nil ( s m u d _ r I ))
( "दौड़" nil ( d au R ))
( "सुअर" nil ( s u a r ))
( "संवैधानिक" nil ( s an v E dh A n i k ))
( "खान" nil ( Kh A n ))
( "खास" nil ( Kh A s ))
( "प्रधान" nil ( p _ r dh A n ))
( "गुजरात" nil ( g u j r A t ))
( "बल्लेबाजी" nil ( b l _ l e b A j I ))
( "लक्षण" nil ( l k _ S N ))
( "र'ग" nil ( r  g ))
( "अच्छा" nil ( a c _ ch A ))
( "अच्छी" nil ( a c _ ch I ))
( "दोस्त" nil ( d o s _ t ))
( "मुफ़्त" nil ( m u f _ t ))
( "देखा" nil ( d e Kh A ))
( "देखे" nil ( d e Kh e ))
( "समझ" nil ( s m jh ))
( "समय" nil ( s m y ))
( "बचाव" nil ( b c A v ))
( "उपस्थिति" nil ( u p s _ th i t i ))
( "नुकसान" nil ( n u k s A n ))
( "खुराक" nil ( Kh u r A k ))
( "अधिकांश" nil ( a dh i k A an S ))
( "धूसर" nil ( dh U s r ))
( "सामान्य" nil ( s A m A n _ y ))
( "घरेलू" nil ( Gh r e l U ))
( "सांसद" nil ( s A an s d ))
( "रक़्स-आ" nil ( r kh _ s A ))
( "कर्मचारी" nil ( k r _ m c A r I ))
( "विभिंन" nil ( v i bh i an n ))
( "घुमाव" nil ( Gh u m A v ))
( "अंतर्गत" nil ( a an t r _ g t ))
( "खोदने" nil ( Kh o d n e ))
( "ऊंट" nil ( U an T ))
( "हाथी" nil ( h A th I ))
( "परिवार" nil ( p r i v A r ))
( "मछली" nil ( m ch l I ))
( "उल्लेख" nil ( u l _ l e Kh ))
( "माध्यम" nil ( m A dh _ y m ))
( "अनुसंधान" nil ( a n u s an dh A n ))
( "वर^" nil ( v  r ))
( "राष्ट्रीय" nil ( r A S _ T _ r I y ))
( "एक" nil ( e  k ))
( "एच" nil ( e  c ))
( "एन" nil ( e  n ))
( "एफ" nil ( e  ph ))
( "एम" nil ( e  m ))
( "एल" nil ( e  l ))
( "एस" nil ( e  s ))
( "विज्न्य'आन" nil ( v i j _ n _ y A n ))
( "पैर" nil ( p E r ))
( "रचना" nil ( r c n A ))
( "राज" nil ( r A j ))
( "रात" nil ( r A t ))
( "मोटा" nil ( m o T A ))
( "मोटी" nil ( m o T I ))
( "राय" nil ( r A y ))
( "लद्र~अके" nil ( l d _ r a k e ))
( "बजे" nil ( b j e ))
( "हम" nil ( h  m ))
( "हर" nil ( h  r ))
( "ही" nil ( h  I ))
( "हे" nil ( h  e ))
( "है" nil ( h  E ))
( "हो" nil ( h  o ))
( "सरकारों" nil ( s r k A r o an ))
( "केंद्र" nil ( k e an d _ r ))
( "निदेशक" nil ( n i d e S k ))
( "अध्ययन" nil ( a dh _ y y n ))
( "अनुरोध" nil ( a n u r o dh ))
( "खून" nil ( Kh U n ))
( "खूब" nil ( Kh U b ))
( "वस्तु" nil ( v s _ t u ))
( "बंगाल" nil ( b an g A l ))
( "महत्वपूर्ण" nil ( m h t _ v p U r _ N ))
( "आयोग" nil ( A y o g ))
( "मंत्र" nil ( m an t _ r ))
( "परामर्श" nil ( p r A m r _ S ))
( "स्थित" nil ( s _ th i t ))
( "महोदय" nil ( m h o d y ))
( "अस्थिरता" nil ( a s _ th i r t A ))
( "योग्य" nil ( y o g _ y ))
( "तत्व" nil ( t t _ v ))
( "लेते" nil ( l e t e ))
( "परिष्कृत" nil ( p r i S _ k ri t ))
( "लिखित" nil ( l i Kh i t ))
( "सलाहकार" nil ( s l A h k A r ))
( "दर" nil ( d  r ))
( "दी" nil ( d  I ))
( "दो" nil ( d  o ))
( "लिए," nil ( l i e ))
( "तालाब" nil ( t A l A b ))
( "शोध" nil ( S o dh ))
( "शोर" nil ( S o r ))
( "पुरुषों" nil ( p u r u S o an ))
( "लगता" nil ( l g t A ))
( "अधिकारी" nil ( a dh i k A r I ))
( "अपना" nil ( a p n A ))
( "अपनी" nil ( a p n I ))
( "अपने" nil ( a p n e ))
( "बुराई" nil ( b u r A I ))
( "पहुंचे." nil ( p h u an c e ))
( "निराश" nil ( n i r A S ))
( "किंतु" nil ( k i an t u ))
( "कहाँ" nil ( k h A l ))
( "कहां" nil ( k h A an ))
( "बारह" nil ( b A r h ))
( "बारे" nil ( b A r e ))
( "रखें" nil ( r Kh e an ))
( "वही" nil ( v h I ))
( "मालूम." nil ( m A l U m ))
( "भूमिका" nil ( bh U m i k A ))
( "इंदौर" nil ( i an d au r ))
( "हैसियत" nil ( h E s i y t ))
( "व्यक्ति" nil ( v _ y k _ t i ))
( "ओर" nil ( o  r ))
( ".कानून" nil ( k A n U n ))
( "चार" nil ( c A r ))
( "चाल" nil ( c A l ))
( "पानी" nil ( p A n I ))
( "परिश्रमी" nil ( p r i S _ r m I ))
( "मालिक" nil ( m A l i k ))
( "रूप" nil ( r U p ))
( "पुन:" nil ( p u n ))
( "आरोग्य" nil ( A r o g _ y ))
( "बताने" nil ( b t A n e ))
