("acreditados" nil (a k r e d i t a d o s))
("adrs" nil (a d r s))
("afp" nil (a f p))
("aib" nil (a i b))
("al" nil (a l))
("asoif" nil (a s o i f))
("asr" nil (a s rr))
("ach" nil (a ch))
("achgabat" nil (a ch g a b a t))
("actriz" nil (a k t r i th))
("además" nil (a d e m a s))
("adiós" nil (a d i o s))
("afganistán" nil (a f g a n i s t a n))
("agrupacion" nil (a g r u p a th i o n))
("ahora" nil (a o r a))
("ahorra" nil (a o rr a))
("ahí" nil (a i))
("akiva" nil (a k i v a))
("al" nil (a l))
("alcalde" nil (a l k a l d e))
("alcalá" nil (a l k a l a))
("algo" nil (a l g o))
("algunos" nil (a l g u n o s))
("alkis" nil (a l k i s))
("ambas" nil (a m b a s))
("amberes" nil (a m b e r e s))
("antonov" nil (a n t o n o v))
("análisis" nil (a n a l i s i s))
("aplaude" nil (a p l a u d e))
("aplauden" nil (a p l a u d e n))
("apoyan" nil (a p o y a n))
("aquí" nil (a k i))
("asimismo" nil (a s i m i s m o))
("así" nil (a s i))
("av" nil (a v))
("ayd" nil (a i d))
("bbv" nil (b b v))
("bfi" nil (b f i))
("babahaj" nil (b a b a a j))
("bafyau" nil (b a f y a u))
("bajo" nil (b a j o))
("bancos" nil (b a n k o s))
("barón" nil (b a r o n))
("basura" nil (b a s u r a))
("bebeto" nil (b e b e t o))
("berasategui" nil (b e r a s a t e g i))
("bergerac" nil (b e r j e r a k))
("berzin" nil (b e r th i n))
("biaggio" nil (b i a g j i o))
("bney" nil (b n e i))
("bochum" nil (b o ch u m))
("borislav" nil (b o r i s l a v))
("breme" nil (b r e m e))
("brujas" nil (b r u j a s))
("bucarest" nil (b u k a r e s t))
("bujsaim" nil (b u j s a i m))
("buscará" nil (b u s k a r a))
("capacidad" nil (k a p a th i d a d))
("cfe" nil (k f e))
("cn" nil (k n))
("cnp" nil (k n p))
("coi" nil (k o i))
("cpp" nil (k p p))
("csg" nil (k s g))
("cuando" nil (k u a n d o))
("campeón" nil (k a m p e o n))
("canadá" nil (k a n a d a))
("caniggia" nil (k a n i g j i a))
("carlota" nil (k a r l o t a))
("carnaval" nil (k a r n a v a l))
("castellblanch" nil (k a s t e ll b l a n ch))
("caterva" nil (k a t e r v a))
("cañizares" nil (k a ny i th a r e s))
("centerpoint" nil (th e n t e r p o i n t))
("ch" nil (ch))
("chaab" nil (ch a a b))
("chalina" nil (ch a l i n a))
("chapultepec" nil (ch a p u l t e p e k))
("chedaiev" nil (ch e d a i e v))
("cherbourg" nil (ch e r b o u r g))
("choques" nil (ch o k e s))
("chrétien" nil (ch r e t i e n))
("chávez" nil (ch a v e th))
("clasificación" nil (k l a s i f i k a th i o n))
("coahuila" nil (k o a u i l a))
("codesal" nil (k o d e s a l))
("compañía" nil (k o m p a ny i a))
("comunidad" nil (k o m u n i d a d))
("confíam" nil (k o n f i a m))
("consejo" nil (k o n s e j o))
("consideramos" nil (k o n s i d e r a m o s))
("consideraron" nil (k o n s i d e r a r o n))
("considero" nil (k o n s i d e r o))
("continúo" nil (k o n t i n u o))
("corazón" nil (k o r a th o n))
("cordobés" nil (k o r d o b e s))
("corría" nil (k o rr i a))
("cortázar" nil (k o r t a th a r))
("cuando" nil (k u a n d o))
("cuatro" nil (k u a t r o))
("cuentan" nil (k u e n t a n))
("curazao" nil (k u r a th a o))
("cárdenas" nil (k a r d e n a s))
("círculo" nil (th i r k u l o))
("deportes" nil (d e p o r t e s))
("df" nil (d f))
("dif" nil (d i f))
("drl" nil (d r l))
("dalorso" nil (d a l o r s o))
("de" nil (d e))
("declinando" nil (d e k l i n a n d o))
("decídete" nil (d e th i d e t e))
("democrático" nil (d e m o k r a t i k o))
("deneuve" nil (d e n e u v e))
("denuncia" nil (d e n u n th i a))
("desarrolla" nil (d e s a rr o ll a))
("desde" nil (d e s d e))
("después" nil (d e s p u e s))
("detectar" nil (d e t e k t a r))
("dicen" nil (d i th e n))
("división" nil (d i v i s i o n))
("djukic" nil (d j u k i k))
("dottuev" nil (d o t t u e v))
("doña" nil (d o ny a))
("dra" nil (d r a))
("dudaiev" nil (d u d a i e v))
("eeuu" nil (e e u u))
("eic" nil (e i k))
("el" nil (e l))
("erp" nil (e r p))
("estados" nil (e s t a d o s))
("eu" nil (e u))
("edgardo" nil (e d g a r d o))
("ekeren" nil (e k e r e n))
("el" nil (e l))
("elracconto" nil (e l r a k k o n t o))
("eliminan" nil (e l i m i n a n))
("ellos" nil (e ll o s))
("elías" nil (e l i a s))
("emiliano" nil (e m i l i a n o))
("en" nil (e n))
("entonces" nil (e n t o n th e s))
("entré" nil (e n t r e))
("es" nil (e s))
("esas" nil (e s a s))
("ese" nil (e s e))
("eso" nil (e s o))
("españa" nil (e s p a ny a))
("espero" nil (e s p e r o))
("espichán" nil (e s p i ch a n))
("estaba" nil (e s t a b a))
("estado" nil (e s t a d o))
("estados" nil (e s t a d o s))
("estamos" nil (e s t a m o s))
("estas" nil (e s t a s))
("esto" nil (e s t o))
("estoscaballeros" nil (e s t o s k a b a ll e r o s))
("estoy" nil (e s t o i))
("estudiará" nil (e s t u d i a r a))
("europea" nil (e u r o p e a))
("evair" nil (e v a i r))
("fbi" nil (f b i))
("fdp" nil (f d p))
("fmf" nil (f m f))
("fmi" nil (f m i))
("fpr" nil (f p r))
("frente" nil (f r e n t e))
("frf" nil (f r f))
("filipinas" nil (f i l i p i n a s))
("fleteros" nil (f l e t e r o s))
("fomcec" nil (f o m th e k))
("foro" nil (f o r o))
("frente" nil (f r e n t e))
("fue" nil (f u e))
("gmt" nil (g m t))
("garcía" nil (g a r th i a))
("gastón" nil (g a s t o n))
("gemelli" nil (j e m e ll i))
("ginebra" nil (j i n e b r a))
("gobierno" nil (g o b i e r n o))
("gonzález" nil (g o n th a l e th))
("gorbachov" nil (g o r b a ch o v))
("gorbatchev" nil (g o r b a t ch e v))
("grimaud" nil (g r i m a u d))
("gueye" nil (g e y e))
("hdtv" nil (d t v))
("haití" nil (a i t i))
("halard" nil (a l a r d))
("hanac" nil (a n a k))
("hidrocapital" nil (i d r o k a p i t a l))
("hierva" nil (i e r v a))
("hija" nil (i j a))
("hriday" nil (r i d a i))
("hristo" nil (r i s t o))
("hubo" nil (u b o))
("huda" nil (u d a))
("huinco" nil (u i n k o))
("héctor" nil (e k t o r))
("ibm" nil (i b m))
("icbf" nil (i k b f))
("ii" nil (i i))
("iii" nil (i i i))
("internamente" nil (i n t e r n a m e n t e))
("intervendra" nil (i n t e r v e n d r a))
("investiga" nil (i n v e s t i g a))
("ip" nil (i p))
("irak" nil (i r a k))
("irna" nil (i r n a))
("iu" nil (i u))
("imola" nil (i m o l a))
("inflación" nil (i n f l a th i o n))
("interesados" nil (i n t e r e s a d o s))
("intertechnique" nil (i n t e r t e ch n i k e))
("ishak" nil (i s a k))
("islamiya" nil (i s l a m i y a))
("iñaki" nil (i ny a k i))
("jce" nil (j th e))
("justos" nil (j u s t o s))
("jabalia" nil (j a b a l i a))
("jamaa" nil (j a m a a))
("japón" nil (j a p o n))
("jasbulatov" nil (j a s b u l a t o v))
("jericó" nil (j e r i k o))
("josé" nil (j o s e))
("jugador" nil (j u g a d o r))
("juri" nil (j u r i))
("juzgado" nil (j u th g a d o))
("km" nil (k m))
("kaige" nil (k a i j e))
("kelloggs" nil (k e ll o g g s))
("kiichpam" nil (k i i ch p a m))
("kornblit" nil (k o r n b l i t))
("kouwenhoven" nil (k o u u e n o v e n))
("kozirev" nil (k o th i r e v))
("kud" nil (k u d))
("kutchma" nil (k u t ch m a))
("kuznetsov" nil (k u th n e t s o v))
("kyoko" nil (k y o k o))
("la" nil (l a))
("la" nil (l a))
("laffaille" nil (l a f f a i ll e))
("larraín" nil (l a rr a i n))
("li" nil (l i))
("liga" nil (l i g a))
("liskow" nil (l i s k o u))
("lituania" nil (l i t u a n i a))
("llegó" nil (ll e g o))
("lloyds" nil (ll o i d s))
("lo" nil (l o))
("logitech" nil (l o j i t e ch))
("logró" nil (l o g r o))
("mdf" nil (m d f))
("militar" nil (m i l i t a r))
("minuar" nil (m i n u a r))
("misericordiosos" nil (m i s e r i k o r d i o s o s))
("mmmm" nil (m m m m))
("mnr" nil (m n rr))
("mte" nil (m t e))
("mvs" nil (m v s))
("machu" nil (m a ch u))
("madinat" nil (m a d i n a t))
("magnasin" nil (m a g n a s i n))
("majmud" nil (m a j m u d))
("marcapomacocha" nil (m a r k a p o m a k o ch a))
("martínez" nil (m a r t i n e th))
("matan" nil (m a t a n))
("maximiliano" nil (m a k s i m i l i a n o))
("mayito" nil (m a y i t o))
("me" nil (m e))
("mejor" nil (m e j o r))
("mejía" nil (m e j i a))
("mihailov" nil (m i a i l o v))
("mijail" nil (m i j a i l))
("milán" nil (m i l a n))
("mladici" nil (m l a d i th i))
("montserrat" nil (m o n t s e rr a t))
("moscú" nil (m o s k u))
("mr" nil (m r))
("muchos" nil (m u ch o s))
("mundial" nil (m u n d i a l))
("municipio" nil (m u n i th i p i o))
("museo" nil (m u s e o))
("muñiz" nil (m u ny i th))
("myosotis" nil (m y o s o t i s))
("más" nil (m a s))
("méxico" nil (m e k s i k o))
("mónica" nil (m o n i k a))
("música" nil (m u s i k a))
("nadie" nil (n a d i e))
("nagatsuka" nil (n a g a t s u k a))
("napoleón" nil (n a p o l e o n))
("newells" nil (n e u e ll s))
("nirmal" nil (n i r m a l))
("no" nil (n o))
("noi" nil (n o i))
("nos" nil (n o s))
("notari" nil (n o t a r i))
("notiene" nil (n o t i e n e))
("noviembre" nil (n o v i e m b r e))
("núñez" nil (n u ny e th))
("oecf" nil (o e k f))
("olp" nil (o l p))
("onu" nil (o n u))
("olog" nil (o l o g))
("oponerse" nil (o p o n e r s e))
("otra" nil (o t r a))
("ottey" nil (o t t e i))
("periodistas" nil (p e r i o d i s t a s))
("pib" nil (p i b))
("pje" nil (p j e))
("pna" nil (p n a))
("pnud" nil (p n u d))
("pvc" nil (p v k))
("pyosa" nil (p y o s a))
("pachap" nil (p a ch a p))
("pachuca" nil (p a ch u k a))
("pacífico" nil (p a th i f i k o))
("panagoulias" nil (p a n a g o u l i a s))
("partes" nil (p a r t e s))
("parís" nil (p a r i s))
("paulatinamente" nil (p a u l a t i n a m e n t e))
("pbro" nil (p b r o))
("pequeño" nil (p e k e ny o))
("permanecía" nil (p e r m a n e th i a))
("perú" nil (p e r u))
("peñaherrera" nil (p e ny a e rr e r a))
("pflugler" nil (p f l u g l e r))
("picchu" nil (p i k ch u))
("piden" nil (p i d e n))
("pienso" nil (p i e n s o))
("piotre" nil (p i o t r e))
("pirata" nil (p i r a t a))
("pistones" nil (p i s t o n e s))
("platense" nil (p l a t e n s e))
("podemos" nil (p o d e m o s))
("pompadura" nil (p o m p a d u r a))
("poptsov" nil (p o p t s o v))
("porque" nil (p o r k e))
("presidenta" nil (p r e s i d e n t a))
("presidente" nil (p r e s i d e n t e))
("primera" nil (p r i m e r a))
("principito" nil (p r i n th i p i t o))
("procuraduría" nil (p r o k u r a d u r i a))
("puede" nil (p u e d e))
("puneño" nil (p u n e ny o))
("puro" nil (p u r o))
("pyonyang" nil (p y o n y a n g))
("pérez" nil (p e r e th))
("quim" nil (k i m))
("qué" nil (k e))
("rdi" nil (rr d i))
("refuerza" nil (rr e f u e r th a))
("rfa" nil (rr f a))
("rn" nil (rr n))
("rtr" nil (rr t r))
("ramzi" nil (rr a m th i))
("ramírez" nil (rr a m i r e th))
("ratko" nil (rr a t k o))
("rayuela" nil (rr a y u e l a))
("raúl" nil (rr a u l))
("realmente" nil (rr e a l m e n t e))
("recuadro" nil (rr e k u a d r o))
("rennes" nil (rr e n n e s))
("rensburg" nil (rr e n s b u r g))
("revolución" nil (rr e v o l u th i o n))
("rhotemberg" nil (rr o t e m b e r g))
("rodríguez" nil (rr o d r i g e th))
("ronaldo" nil (rr o n a l d o))
("ruhengeri" nil (rr u e n j e r i))
("ríos" nil (rr i o s))
("sct" nil (s k t))
("seamos" nil (s e a m o s))
("setubal" nil (s e t u b a l))
("si" nil (s i))
("su" nil (s u))
("sadam" nil (s a d a m))
("saib" nil (s a i b))
("saidi" nil (s a i d i))
("salam" nil (s a l a m))
("sampdoria" nil (s a m p d o r i a))
("schloemann" nil (s ch l o e m a n n))
("se" nil (s e))
("secretario" nil (s e k r e t a r i o))
("según" nil (s e g u n))
("serguei" nil (s e r g e i))
("serrizuela" nil (s e rr i th u e l a))
("será" nil (s e r a))
("sería" nil (s e r i a))
("sexta" nil (s e s t a))
("seyaj" nil (s e y a j))
("señaló" nil (s e ny a l o))
("señor" nil (s e ny o r))
("si" nil (s i))
("siemag" nil (s i e m a g))
("siempre" nil (s i e m p r e))
("siento" nil (s i e n t o))
("sigo" nil (s i g o))
("siguen" nil (s i g e n))
("simplemente" nil (s i m p l e m e n t e))
("simón" nil (s i m o n))
("sofía" nil (s o f i a))
("solidaridad" nil (s o l i d a r i d a d))
("staubach" nil (s t a u b a ch))
("steaua" nil (s t e a u a))
("stelea" nil (s t e l e a))
("stoichkov" nil (s t o i ch k o v))
("su" nil (s u))
("subrayó" nil (s u b r a y o))
("suiza" nil (s u i th a))
("supervga" nil (s u p e r v g a))
("sánchez" nil (s a n ch e th))
("sé" nil (s e))
("tlc" nil (t l k))
("tqm" nil (t k m))
("transmitido" nil (t r a n s m i t i d o))
("tv" nil (t v))
("taiwán" nil (t a i u a n))
("también" nil (t a m b i e n))
("tami" nil (t a m i))
("telefónica" nil (t e l e f o n i k a))
("teme" nil (t e m e))
("tengo" nil (t e n g o))
("todos" nil (t o d o s))
("toullier" nil (t o u ll i e r))
("trabajadores" nil (t r a b a j a d o r e s))
("traición" nil (t r a i th i o n))
("trazado" nil (t r a th a d o))
("tres" nil (t r e s))
("treviño" nil (t r e v i ny o))
("turkménistán" nil (t u r k m e n i s t a n))
("ue" nil (u e))
("ugt" nil (u g t))
("unidos" nil (u n i d o s))
("ubillús" nil (u b i ll u s))
("ucrania" nil (u k r a n i a))
("ud" nil (u d))
("ugrumov" nil (u g r u m o v))
("un" nil (u n))
("unas" nil (u n a s))
("unidos" nil (u n i d o s))
("universitario" nil (u n i v e r s i t a r i o))
("usando" nil (u s a n d o))
("usarán" nil (u s a r a n))
("usted" nil (u s t e d))
("usuriaga" nil (u s u r i a g a))
("vez" nil (v e th))
("vitoria" nil (v i t o r i a))
("vudu" nil (v u d u))
("vvf" nil (v v f))
("vw" nil (v u))
("vahirua" nil (v a i r u a))
("vakonieva" nil (v a k o n i e v a))
("valioso" nil (v a l i o s o))
("verdad" nil (v e r d a d))
("veían" nil (v e i a n))
("viendo" nil (v i e n d o))
("visiblemente" nil (v i s i b l e m e n t e))
("vite" nil (v i t e))
("we" nil (u e))
("wendlinger" nil (u e n d l i n j e r))
("whitlinger" nil (u i t l i n j e r))
("xxi" nil (s k s i))
("ya" nil (y a))
("ya" nil (y a))
("yadira" nil (y a d i r a))
("yihad" nil (y i a d))
("yo" nil (y o))
("yucatán" nil (y u k a t a n))
("yucef" nil (y u th e f))
("yuran" nil (y u r a n))
("zanjas" nil (th a n j a s))
("zúñiga" nil (th u ny i g a))
("abandonar" nil (a b a n d o n a r))
("abdicación" nil (a b d i k a th i o n))
("abjasia" nil (a b j a s i a))
("abogado" nil (a b o g a d o))
("abolirá" nil (a b o l i r a))
("abrevó" nil (a b r e v o))
("abridor" nil (a b r i d o r))
("absoluto" nil (a b s o l u t o))
("abusos" nil (a b u s o s))
("acabar" nil (a k a b a r))
("accidente" nil (a k th i d e n t e))
("accidentes" nil (a k th i d e n t e s))
("accionar" nil (a k th i o n a r))
("accionistas" nil (a k th i o n i s t a s))
("acción" nil (a k th i o n))
("aceptaba" nil (a th e p t a b a))
("aceptado" nil (a th e p t a d o))
("aceptar" nil (a th e p t a r))
("acerca" nil (a th e r k a))
("acercado" nil (a th e r k a d o))
("acidez" nil (a th i d e th))
("acompañaba" nil (a k o m p a ny a b a))
("aconsejó" nil (a k o n s e j o))
("acordado" nil (a k o r d a d o))
("actitud" nil (a k t i t u d))
("actividad" nil (a k t i v i d a d))
("acto" nil (a k t o))
("actualizado" nil (a k t u a l i th a d o))
("actualmente" nil (a k t u a l m e n t e))
("actuando" nil (a k t u a n d o))
("actúen" nil (a k t u e n))
("acuerdo" nil (a k u e r d o))
("acusados" nil (a k u s a d o s))
("adejtiuvo" nil (a d e j t i u v o))
("adelantada" nil (a d e l a n t a d a))
("adelantado" nil (a d e l a n t a d o))
("además" nil (a d e m a s))
("adicional" nil (a d i th i o n a l))
("adjudicó" nil (a d j u d i k o))
("adoptan" nil (a d o p t a n))
("adquisición" nil (a d k i s i th i o n))
("adulto" nil (a d u l t o))
("adultos" nil (a d u l t o s))
("adversario" nil (a d v e r s a r i o))
("advertencias" nil (a d v e r t e n th i a s))
("advirtió" nil (a d v i r t i o))
("adyacentes" nil (a d y a th e n t e s))
("aerolíneas" nil (a e r o l i n e a s))
("aeropuerto" nil (a e r o p u e r t o))
("aficionados" nil (a f i th i o n a d o s))
("afirma" nil (a f i r m a))
("afirmar" nil (a f i r m a r))
("afirmaron" nil (a f i r m a r o n))
("afirmó" nil (a f i r m o))
("agencia" nil (a j e n th i a))
("agitaban" nil (a j i t a b a n))
("agosto" nil (a g o s t o))
("agravado" nil (a g r a v a d o))
("agregan" nil (a g r e g a n))
("agregando" nil (a g r e g a n d o))
("agregó" nil (a g r e g o))
("agrícolas" nil (a g r i k o l a s))
("agua" nil (a g u a))
("ahora" nil (a o r a))
("ahorrador" nil (a o rr a d o r))
("ahuyenta" nil (a u y e n t a))
("ahí" nil (a i))
("aire" nil (a i r e))
("al" nil (a l))
("albur" nil (a l b u r))
("alcancé" nil (a l k a n th e))
("alegría" nil (a l e g r i a))
("algo" nil (a l g o))
("alguien" nil (a l g i e n))
("alguna" nil (a l g u n a))
("algunas" nil (a l g u n a s))
("algunos" nil (a l g u n o s))
("alimañas" nil (a l i m a ny a s))
("alimentando" nil (a l i m e n t a n d o))
("alineó" nil (a l i n e o))
("aliviar" nil (a l i v i a r))
("alivio" nil (a l i v i o))
("allí" nil (a ll i))
("alrededor" nil (a l rr e d e d o r))
("alternativa" nil (a l t e r n a t i v a))
("alto" nil (a l t o))
("amado" nil (a m a d o))
("amarme" nil (a m a r m e))
("ambas" nil (a m b a s))
("ambos" nil (a m b o s))
("amenaza" nil (a m e n a th a))
("amenazó" nil (a m e n a th o))
("amistad" nil (a m i s t a d))
("amplia" nil (a m p l i a))
("analista" nil (a n a l i s t a))
("analizándolo" nil (a n a l i th a n d o l o))
("andaban" nil (a n d a b a n))
("andaluzas" nil (a n d a l u th a s))
("andantes" nil (a n d a n t e s))
("animales" nil (a n i m a l e s))
("anonimato" nil (a n o n i m a t o))
("anotado" nil (a n o t a d o))
("anotó" nil (a n o t o))
("ante" nil (a n t e))
("antelación" nil (a n t e l a th i o n))
("antes" nil (a n t e s))
("antibacteriales" nil (a n t i b a k t e r i a l e s))
("antiflama" nil (a n t i f l a m a))
("antigua" nil (a n t i g u a))
("antitanque" nil (a n t i t a n k e))
("anunció" nil (a n u n th i o))
("anónimo" nil (a n o n i m o))
("apacible" nil (a p a th i b l e))
("apagones" nil (a p a g o n e s))
("apenas" nil (a p e n a s))
("apertura" nil (a p e r t u r a))
("apetecibles" nil (a p e t e th i b l e s))
("aplaudido" nil (a p l a u d i d o))
("aplauso" nil (a p l a u s o))
("apodo" nil (a p o d o))
("aportada" nil (a p o r t a d a))
("apoyará" nil (a p o y a r a))
("apoyo" nil (a p o y o))
("aprobada" nil (a p r o b a d a))
("aquel" nil (a k e l))
("aquella" nil (a k e ll a))
("aquí" nil (a k i))
("arma" nil (a r m a))
("armada" nil (a r m a d a))
("arquero" nil (a r k e r o))
("arrancar" nil (a rr a n k a r))
("arreglan" nil (a rr e g l a n))
("arrestado" nil (a rr e s t a d o))
("arroja" nil (a rr o j a))
("articulado" nil (a r t i k u l a d o))
("artista" nil (a r t i s t a))
("artículos" nil (a r t i k u l o s))
("asaltados" nil (a s a l t a d o s))
("asalto" nil (a s a l t o))
("aseguró" nil (a s e g u r o))
("asesinato" nil (a s e s i n a t o))
("asignación" nil (a s i g n a th i o n))
("asistir" nil (a s i s t i r))
("asunto" nil (a s u n t o))
("así" nil (a s i))
("atemorizar" nil (a t e m o r i th a r))
("atenerrme" nil (a t e n e rr m e))
("atentado" nil (a t e n t a d o))
("atentados" nil (a t e n t a d o s))
("atentiguan" nil (a t e n t i g u a n))
("aterrizaje" nil (a t e rr i th a j e))
("auge" nil (a u j e))
("aumente" nil (a u m e n t e))
("aumento" nil (a u m e n t o))
("aunque" nil (a u n k e))
("auto" nil (a u t o))
("autonomía" nil (a u t o n o m i a))
("autoridades" nil (a u t o r i d a d e s))
("avalúo" nil (a v a l u o))
("avistó" nil (a v i s t o))
("ayer" nil (a y e r))
("ayuda" nil (a y u d a))
("ayudamos" nil (a y u d a m o s))
("ayudar" nil (a y u d a r))
("azucarera" nil (a th u k a r e r a))
("azufre" nil (a th u f r e))
("aéreos" nil (a e r e o s))
("añade" nil (a ny a d e))
("año" nil (a ny o))
("años" nil (a ny o s))
("aún" nil (a u n))
("bailando" nil (b a i l a n d o))
("bajaron" nil (b a j a r o n))
("bajas" nil (b a j a s))
("bajo" nil (b a j o))
("bajos" nil (b a j o s))
("balcón" nil (b a l k o n))
("baldío" nil (b a l d i o))
("balón" nil (b a l o n))
("bandos" nil (b a n d o s))
("banqueta" nil (b a n k e t a))
("bar" nil (b a r))
("barreras" nil (b a rr e r a s))
("barrio" nil (b a rr i o))
("base" nil (b a s e))
("bases" nil (b a s e s))
("bastante" nil (b a s t a n t e))
("batalla" nil (b a t a ll a))
("batallas" nil (b a t a ll a s))
("batería" nil (b a t e r i a))
("belga" nil (b e l g a))
("benchmarking" nil (b e n ch m a r k i n g))
("bendecida" nil (b e n d e th i d a))
("benigna" nil (b e n i g n a))
("bermellón" nil (b e r m e ll o n))
("bicicleta" nil (b i th i k l e t a))
("bien" nil (b i e n))
("bienes" nil (b i e n e s))
("blanca" nil (b l a n k a))
("blanco" nil (b l a n k o))
("bloqueo" nil (b l o k e o))
("bomba" nil (b o m b a))
("bombardeos" nil (b o m b a r d e o s))
("bonachona" nil (b o n a ch o n a))
("bonaerense" nil (b o n a e r e n s e))
("boom" nil (b o o m))
("bosnio" nil (b o s n i o))
("boxes" nil (b o k s e s))
("bravuconadas" nil (b r a v u k o n a d a s))
("brillantes" nil (b r i ll a n t e s))
("buena" nil (b u e n a))
("burros" nil (b u rr o s))
("bursátil" nil (b u r s a t i l))
("buscaba" nil (b u s k a b a))
("búlgaro" nil (b u l g a r o))
("cabal" nil (k a b a l))
("caballos" nil (k a b a ll o s))
("cabaret" nil (k a b a r e t))
("cabeza" nil (k a b e th a))
("cabizbajo" nil (k a b i th b a j o))
("cabo" nil (k a b o))
("cada" nil (k a d a))
("cadmio" nil (k a d m i o))
("café" nil (k a f e))
("calendario" nil (k a l e n d a r i o))
("calidad" nil (k a l i d a d))
("calificaron" nil (k a l i f i k a r o n))
("calle" nil (k a ll e))
("calles" nil (k a ll e s))
("calma" nil (k a l m a))
("caminos" nil (k a m i n o s))
("camisitas" nil (k a m i s i t a s))
("campeonato" nil (k a m p e o n a t o))
("campo" nil (k a m p o))
("campos" nil (k a m p o s))
("canal" nil (k a n a l))
("canas" nil (k a n a s))
("candidaturas" nil (k a n d i d a t u r a s))
("cantina" nil (k a n t i n a))
("capacitada" nil (k a p a th i t a d a))
("capaciten" nil (k a p a th i t e n))
("capital" nil (k a p i t a l))
("capitán" nil (k a p i t a n))
("captar" nil (k a p t a r))
("capturas" nil (k a p t u r a s))
("características" nil (k a r a k t e r i s t i k a s))
("caras" nil (k a r a s))
("cargamento" nil (k a r g a m e n t o))
("cargo" nil (k a r g o))
("carne" nil (k a r n e))
("carpeta" nil (k a r p e t a))
("carrera" nil (k a rr e r a))
("carreras" nil (k a rr e r a s))
("carro" nil (k a rr o))
("carruaje" nil (k a rr u a j e))
("carta" nil (k a r t a))
("cartel" nil (k a r t e l))
("casa" nil (k a s a))
("casi" nil (k a s i))
("caso" nil (k a s o))
("casos" nil (k a s o s))
("castañuelas" nil (k a s t a ny u e l a s))
("casualidad" nil (k a s u a l i d a d))
("catorce" nil (k a t o r th e))
("cautiverio" nil (k a u t i v e r i o))
("cayó" nil (k a y o))
("cañones" nil (k a ny o n e s))
("celebrarán" nil (th e l e b r a r a n))
("celebró" nil (th e l e b r o))
("centavos" nil (th e n t a v o s))
("central" nil (th e n t r a l))
("centrales" nil (th e n t r a l e s))
("cercó" nil (th e r k o))
("cereales" nil (th e r e a l e s))
("cero" nil (th e r o))
("cerrado" nil (th e rr a d o))
("cerraron" nil (th e rr a r o n))
("cerró" nil (th e rr o))
("ceñidas" nil (th e ny i d a s))
("cheques" nil (ch e k e s))
("chiapaneco" nil (ch i a p a n e k o))
("chiapanos" nil (ch i a p a n o s))
("chico" nil (ch i k o))
("chifón" nil (ch i f o n))
("chilena" nil (ch i l e n a))
("chino" nil (ch i n o))
("chinos" nil (ch i n o s))
("chismosa" nil (ch i s m o s a))
("choca" nil (ch o k a))
("ciclo" nil (th i k l o))
("cien" nil (th i e n))
("ciento" nil (th i e n t o))
("cientos" nil (th i e n t o s))
("cierta" nil (th i e r t a))
("cierto" nil (th i e r t o))
("cinco" nil (th i n k o))
("cincuentai" nil (th i n k u e n t a i))
("cinematografías" nil (th i n e m a t o g r a f i a s))
("circuito" nil (th i r k u i t o))
("circulaban" nil (th i r k u l a b a n))
("ciudad" nil (th i u d a d))
("ciudadanía" nil (th i u d a d a n i a))
("civil" nil (th i v i l))
("civiles" nil (th i v i l e s))
("claro" nil (k l a r o))
("clasificación" nil (k l a s i f i k a th i o n))
("club" nil (k l u b))
("coahuilense" nil (k o a u i l e n s e))
("cohetitos" nil (k o e t i t o s))
("colaboradores" nil (k o l a b o r a d o r e s))
("colegas" nil (k o l e g a s))
("colgaban" nil (k o l g a b a n))
("colmar" nil (k o l m a r))
("colocado" nil (k o l o k a d o))
("colocados" nil (k o l o k a d o s))
("colores" nil (k o l o r e s))
("comandante" nil (k o m a n d a n t e))
("combustible" nil (k o m b u s t i b l e))
("comentario" nil (k o m e n t a r i o))
("comentarios" nil (k o m e n t a r i o s))
("comenzaron" nil (k o m e n th a r o n))
("comenzará" nil (k o m e n th a r a))
("comenzó" nil (k o m e n th o))
("comercial" nil (k o m e r th i a l))
("comerciales" nil (k o m e r th i a l e s))
("comercialismo" nil (k o m e r th i a l i s m o))
("comercio" nil (k o m e r th i o))
("comienzo" nil (k o m i e n th o))
("comisión" nil (k o m i s i o n))
("como" nil (k o m o))
("compañera" nil (k o m p a ny e r a))
("compañero" nil (k o m p a ny e r o))
("compañia" nil (k o m p a ny i a))
("compañía" nil (k o m p a ny i a))
("compitiendo" nil (k o m p i t i e n d o))
("completamente" nil (k o m p l e t a m e n t e))
("complica" nil (k o m p l i k a))
("complicación" nil (k o m p l i k a th i o n))
("comprada" nil (k o m p r a d a))
("comprobar" nil (k o m p r o b a r))
("compromiso" nil (k o m p r o m i s o))
("computacional" nil (k o m p u t a th i o n a l))
("comunicación" nil (k o m u n i k a th i o n))
("comunicado" nil (k o m u n i k a d o))
("comunicantes" nil (k o m u n i k a n t e s))
("con" nil (k o n))
("conciliación" nil (k o n th i l i a th i o n))
("conclusiones" nil (k o n k l u s i o n e s))
("concubina" nil (k o n k u b i n a))
("condiciones" nil (k o n d i th i o n e s))
("condición" nil (k o n d i th i o n))
("confeccionados" nil (k o n f e k th i o n a d o s))
("confesó" nil (k o n f e s o))
("confianza" nil (k o n f i a n th a))
("confiesa" nil (k o n f i e s a))
("conflicto" nil (k o n f l i k t o))
("conjunto" nil (k o n j u n t o))
("conseguido" nil (k o n s e g i d o))
("conservador" nil (k o n s e r v a d o r))
("considera" nil (k o n s i d e r a))
("consideran" nil (k o n s i d e r a n))
("constante" nil (k o n s t a n t e))
("constituyó" nil (k o n s t i t u y o))
("construirá" nil (k o n s t r u i r a))
("consumado" nil (k o n s u m a d o))
("contadas" nil (k o n t a d a s))
("contar" nil (k o n t a r))
("contento" nil (k o n t e n t o))
("contiene" nil (k o n t i e n e))
("continuar" nil (k o n t i n u a r))
("continuará" nil (k o n t i n u a r a))
("contra" nil (k o n t r a))
("contrarreloj" nil (k o n t r a rr e l o j))
("contrato" nil (k o n t r a t o))
("control" nil (k o n t r o l))
("conurbada" nil (k o n u r b a d a))
("conversación" nil (k o n v e r s a th i o n))
("convertido" nil (k o n v e r t i d o))
("convertirá" nil (k o n v e r t i r a))
("convierta" nil (k o n v i e r t a))
("convirtió" nil (k o n v i r t i o))
("copa" nil (k o p a))
("coronas" nil (k o r o n a s))
("corporativos" nil (k o r p o r a t i v o s))
("correctamente" nil (k o rr e k t a m e n t e))
("correr" nil (k o rr e r))
("correspondiente" nil (k o rr e s p o n d i e n t e))
("corrida" nil (k o rr i d a))
("corriente" nil (k o rr i e n t e))
("corrupción" nil (k o rr u p th i o n))
("cortarlos" nil (k o r t a r l o s))
("cosa" nil (k o s a))
("costo" nil (k o s t o))
("cotejo" nil (k o t e j o))
("cotinúa" nil (k o t i n u a))
("coucheo" nil (k o u ch e o))
("crack" nil (k r a k k))
("crear" nil (k r e a r))
("crece" nil (k r e th e))
("crecida" nil (k r e th i d a))
("creciendo" nil (k r e th i e n d o))
("crecimiento" nil (k r e th i m i e n t o))
("crecio" nil (k r e th i o))
("crediticias" nil (k r e d i t i th i a s))
("crema" nil (k r e m a))
("cremera" nil (k r e m e r a))
("creo" nil (k r e o))
("cretinismo" nil (k r e t i n i s m o))
("crisis" nil (k r i s i s))
("criticado" nil (k r i t i k a d o))
("cruza" nil (k r u th a))
("créditos" nil (k r e d i t o s))
("críticos" nil (k r i t i k o s))
("cual" nil (k u a l))
("cuales" nil (k u a l e s))
("cualquier" nil (k u a l k i e r))
("cualquiera" nil (k u a l k i e r a))
("cuando" nil (k u a n d o))
("cuarenta" nil (k u a r e n t a))
("cuarentai" nil (k u a r e n t a i))
("cuarta" nil (k u a r t a))
("cuarto" nil (k u a r t o))
("cuartos" nil (k u a r t o s))
("cuatro" nil (k u a t r o))
("cubren" nil (k u b r e n))
("cuchillos" nil (k u ch i ll o s))
("cucú" nil (k u k u))
("cuenta" nil (k u e n t a))
("cuerpo" nil (k u e r p o))
("cultores" nil (k u l t o r e s))
("cumplen" nil (k u m p l e n))
("cumplir" nil (k u m p l i r))
("cálido" nil (k a l i d o))
("cáncer" nil (k a n th e r))
("cárcel" nil (k a r th e l))
("cívico" nil (th i v i k o))
("cóconas" nil (k o k o n a s))
("cómo" nil (k o m o))
("cómodos" nil (k o m o d o s))
("cónyuge" nil (k o n y u j e))
("dado" nil (d a d o))
("danzas" nil (d a n th a s))
("darle" nil (d a r l e))
("dasr" nil (d a s rr))
("daños" nil (d a ny o s))
("de" nil (d e))
("desouvenirs" nil (d e s o u v e n i r s))
("debe" nil (d e b e))
("deben" nil (d e b e n))
("deberá" nil (d e b e r a))
("deberán" nil (d e b e r a n))
("decente" nil (d e th e n t e))
("deciden" nil (d e th i d e n))
("decidido" nil (d e th i d i d o))
("decir" nil (d e th i r))
("decisión" nil (d e th i s i o n))
("declaró" nil (d e k l a r o))
("decreto" nil (d e k r e t o))
("decía" nil (d e th i a))
("defendida" nil (d e f e n d i d a))
("definidas" nil (d e f i n i d a s))
("definitiva" nil (d e f i n i t i v a))
("definitivo" nil (d e f i n i t i v o))
("dejó" nil (d e j o))
("del" nil (d e l))
("delantero" nil (d e l a n t e r o))
("delegados" nil (d e l e g a d o s))
("delito" nil (d e l i t o))
("demagogia" nil (d e m a g o j i a))
("demasiado" nil (d e m a s i a d o))
("demostrado" nil (d e m o s t r a d o))
("demás" nil (d e m a s))
("dentro" nil (d e n t r o))
("denunció" nil (d e n u n th i o))
("departamentales" nil (d e p a r t a m e n t a l e s))
("departamento" nil (d e p a r t a m e n t o))
("dependencias" nil (d e p e n d e n th i a s))
("depositaba" nil (d e p o s i t a b a))
("derecho" nil (d e r e ch o))
("derrota" nil (d e rr o t a))
("derrotó" nil (d e rr o t o))
("desaparecido" nil (d e s a p a r e th i d o))
("desapareció" nil (d e s a p a r e th i o))
("desaprovechó" nil (d e s a p r o v e ch o))
("desarrrollo" nil (d e s a rr r o ll o))
("desbarata" nil (d e s b a r a t a))
("descansada" nil (d e s k a n s a d a))
("descartó" nil (d e s k a r t o))
("descompuso" nil (d e s k o m p u s o))
("desconsuelo" nil (d e s k o n s u e l o))
("describe" nil (d e s k r i b e))
("desde" nil (d e s d e))
("desertarán" nil (d e s e r t a r a n))
("desfasando" nil (d e s f a s a n d o))
("desfilaron" nil (d e s f i l a r o n))
("desgracias" nil (d e s g r a th i a s))
("despcho" nil (d e s p ch o))
("despertaba" nil (d e s p e r t a b a))
("después" nil (d e s p u e s))
("destapados" nil (d e s t a p a d o s))
("destinaban" nil (d e s t i n a b a n))
("destinado" nil (d e s t i n a d o))
("destitución" nil (d e s t i t u th i o n))
("destrucción" nil (d e s t r u k th i o n))
("destructiva" nil (d e s t r u k t i v a))
("destruida" nil (d e s t r u i d a))
("detenciones" nil (d e t e n th i o n e s))
("detener" nil (d e t e n e r))
("detenido" nil (d e t e n i d o))
("detenidos" nil (d e t e n i d o s))
("determinación" nil (d e t e r m i n a th i o n))
("detonación" nil (d e t o n a th i o n))
("detuvieron" nil (d e t u v i e r o n))
("diagnóstico" nil (d i a g n o s t i k o))
("diaria" nil (d i a r i a))
("dice" nil (d i th e))
("dicen" nil (d i th e n))
("diciembre" nil (d i th i e m b r e))
("did" nil (d i d))
("dieci" nil (d i e th i))
("diez" nil (d i e th))
("difícil" nil (d i f i th i l))
("digestivos" nil (d i j e s t i v o s))
("digestión" nil (d i j e s t i o n))
("digno" nil (d i g n o))
("digo" nil (d i g o))
("dijera" nil (d i j e r a))
("dijeron" nil (d i j e r o n))
("dijo" nil (d i j o))
("dinero" nil (d i n e r o))
("dio" nil (d i o))
("diplomado" nil (d i p l o m a d o))
("diplomático" nil (d i p l o m a t i k o))
("diputados" nil (d i p u t a d o s))
("directivos" nil (d i r e k t i v o s))
("director" nil (d i r e k t o r))
("directos" nil (d i r e k t o s))
("dirigente" nil (d i r i j e n t e))
("dirigía" nil (d i r i j i a))
("dirimirán" nil (d i r i m i r a n))
("disciplinada" nil (d i s th i p l i n a d a))
("discutir" nil (d i s k u t i r))
("disidentes" nil (d i s i d e n t e s))
("dispone" nil (d i s p o n e))
("dispositivo" nil (d i s p o s i t i v o))
("dispuesta" nil (d i s p u e s t a))
("disputables" nil (d i s p u t a b l e s))
("disputado" nil (d i s p u t a d o))
("distribución" nil (d i s t r i b u th i o n))
("diversificación" nil (d i v e r s i f i k a th i o n))
("divide" nil (d i v i d e))
("dióxido" nil (d i o k s i d o))
("doce" nil (d o th e))
("docencia" nil (d o th e n th i a))
("doctor" nil (d o k t o r))
("domicilio" nil (d o m i th i l i o))
("domingo" nil (d o m i n g o))
("donde" nil (d o n d e))
("dos" nil (d o s))
("dosis" nil (d o s i s))
("drama" nil (d r a m a))
("dudas" nil (d u d a s))
("dueño" nil (d u e ny o))
("durante" nil (d u r a n t e))
("durará" nil (d u r a r a))
("durazno" nil (d u r a th n o))
("duro" nil (d u r o))
("duros" nil (d u r o s))
("dé" nil (d e))
("décadas" nil (d e k a d a s))
("déficit" nil (d e f i th i t))
("días" nil (d i a s))
("dólares" nil (d o l a r e s))
("dónde" nil (d o n d e))
("echándole" nil (e ch a n d o l e))
("económica" nil (e k o n o m i k a))
("económico" nil (e k o n o m i k o))
("ecotaxistas" nil (e k o t a k s i s t a s))
("edad" nil (e d a d))
("efecto" nil (e f e k t o))
("efectuado" nil (e f e k t u a d o))
("efectuó" nil (e f e k t u o))
("egoístas" nil (e g o i s t a s))
("ejecución" nil (e j e k u th i o n))
("ejecutiva" nil (e j e k u t i v a))
("ejemplo" nil (e j e m p l o))
("ejército" nil (e j e r th i t o))
("el" nil (e l))
("elecciones" nil (e l e k th i o n e s))
("electoral" nil (e l e k t o r a l))
("electorales" nil (e l e k t o r a l e s))
("ellos" nil (e ll o s))
("embarcando" nil (e m b a r k a n d o))
("embarcar" nil (e m b a r k a r))
("emblema" nil (e m b l e m a))
("empaques" nil (e m p a k e s))
("empate" nil (e m p a t e))
("empezando" nil (e m p e th a n d o))
("empezó" nil (e m p e th o))
("empresa" nil (e m p r e s a))
("empresarial" nil (e m p r e s a r i a l))
("empresarios" nil (e m p r e s a r i o s))
("empresas" nil (e m p r e s a s))
("empuñar" nil (e m p u ny a r))
("en" nil (e n))
("encomendada" nil (e n k o m e n d a d a))
("encontraban" nil (e n k o n t r a b a n))
("encontrado" nil (e n k o n t r a d o))
("encontró" nil (e n k o n t r o))
("encuentra" nil (e n k u e n t r a))
("encuentran" nil (e n k u e n t r a n))
("encuentro" nil (e n k u e n t r o))
("enemigo" nil (e n e m i g o))
("enero" nil (e n e r o))
("enfado" nil (e n f a d o))
("enfermo" nil (e n f e r m o))
("enfoque" nil (e n f o k e))
("enfrentan" nil (e n f r e n t a n))
("engendros" nil (e n j e n d r o s))
("enjuto" nil (e n j u t o))
("enriquecido" nil (e n rr i k e th i d o))
("entiéndelo" nil (e n t i e n d e l o))
("entonces" nil (e n t o n th e s))
("entrará" nil (e n t r a r a))
("entre" nil (e n t r e))
("entrenador" nil (e n t r e n a d o r))
("entrenadores" nil (e n t r e n a d o r e s))
("entrenando" nil (e n t r e n a n d o))
("entrevista" nil (e n t r e v i s t a))
("entusiasmo" nil (e n t u s i a s m o))
("enviado" nil (e n v i a d o))
("equipo" nil (e k i p o))
("equipos" nil (e k i p o s))
("era" nil (e r a))
("eres" nil (e r e s))
("erradicar" nil (e rr a d i k a r))
("errores" nil (e rr o r e s))
("es" nil (e s))
("esa" nil (e s a))
("esas" nil (e s a s))
("escabullirse" nil (e s k a b u ll i r s e))
("escalones" nil (e s k a l o n e s))
("escaparse" nil (e s k a p a r s e))
("escasa" nil (e s k a s a))
("escaso" nil (e s k a s o))
("escasos" nil (e s k a s o s))
("escaño" nil (e s k a ny o))
("escaños" nil (e s k a ny o s))
("escocés" nil (e s k o th e s))
("escote" nil (e s k o t e))
("escritor" nil (e s k r i t o r))
("escuchando" nil (e s k u ch a n d o))
("escuchar" nil (e s k u ch a r))
("escuchó" nil (e s k u ch o))
("escuálidas" nil (e s k u a l i d a s))
("eso" nil (e s o))
("esos" nil (e s o s))
("espalda" nil (e s p a l d a))
("español" nil (e s p a ny o l))
("especial" nil (e s p e th i a l))
("especialidad" nil (e s p e th i a l i d a d))
("especialista" nil (e s p e th i a l i s t a))
("espectáculo" nil (e s p e k t a k u l o))
("esperaba" nil (e s p e r a b a))
("esposo" nil (e s p o s o))
("esta" nil (e s t a))
("estaba" nil (e s t a b a))
("establecido" nil (e s t a b l e th i d o))
("estado" nil (e s t a d o))
("estamos" nil (e s t a m o s))
("estar" nil (e s t a r))
("estas" nil (e s t a s))
("estatal" nil (e s t a t a l))
("este" nil (e s t e))
("estemos" nil (e s t e m o s))
("estilos" nil (e s t i l o s))
("estimó" nil (e s t i m o))
("estomacal" nil (e s t o m a k a l))
("estos" nil (e s t o s))
("estoy" nil (e s t o i))
("estrategia" nil (e s t r a t e j i a))
("estrepitoso" nil (e s t r e p i t o s o))
("estructura" nil (e s t r u k t u r a))
("estudios" nil (e s t u d i o s))
("estuvo" nil (e s t u v o))
("está" nil (e s t a))
("están" nil (e s t a n))
("etapa" nil (e t a p a))
("etapas" nil (e t a p a s))
("etc" nil (e t k))
("euforia" nil (e u f o r i a))
("evento" nil (e v e n t o))
("evitar" nil (e v i t a r))
("evitaron" nil (e v i t a r o n))
("evocó" nil (e v o k o))
("evolución" nil (e v o l u th i o n))
("ex" nil (e k s))
("excelente" nil (e s th e l e n t e))
("exceso" nil (e s th e s o))
("existe" nil (e k s i s t e))
("exitosamente" nil (e k s i t o s a m e n t e))
("experiencia" nil (e s p e r i e n th i a))
("expertos" nil (e s p e r t o s))
("explica" nil (e s p l i k a))
("explicación" nil (e s p l i k a th i o n))
("explicó" nil (e s p l i k o))
("explora" nil (e s p l o r a))
("explosión" nil (e s p l o s i o n))
("explotación" nil (e s p l o t a th i o n))
("explotó" nil (e s p l o t o))
("exponente" nil (e s p o n e n t e))
("exposición" nil (e s p o s i th i o n))
("expresó" nil (e s p r e s o))
("expuestos" nil (e s p u e s t o s))
("extenuante" nil (e s t e n u a n t e))
("extracciones" nil (e s t r a k th i o n e s))
("fabricados" nil (f a b r i k a d o s))
("fabricante" nil (f a b r i k a n t e))
("factores" nil (f a k t o r e s))
("falllas" nil (f a ll l a s))
("faltaron" nil (f a l t a r o n))
("fama" nil (f a m a))
("familia" nil (f a m i l i a))
("famosos" nil (f a m o s o s))
("farmacéuticas" nil (f a r m a th e u t i k a s))
("favor" nil (f a v o r))
("favorables" nil (f a v o r a b l e s))
("favoritas" nil (f a v o r i t a s))
("febrero" nil (f e b r e r o))
("fecha" nil (f e ch a))
("felicitó" nil (f e l i th i t o))
("feliz" nil (f e l i th))
("fertilizante" nil (f e r t i l i th a n t e))
("fianza" nil (f i a n th a))
("ficha" nil (f i ch a))
("fiesta" nil (f i e s t a))
("figura" nil (f i g u r a))
("figuraba" nil (f i g u r a b a))
("fijado" nil (f i j a d o))
("fin" nil (f i n))
("final" nil (f i n a l))
("fino" nil (f i n o))
("firmado" nil (f i r m a d o))
("firmar" nil (f i r m a r))
("firme" nil (f i r m e))
("firmemente" nil (f i r m e m e n t e))
("firmó" nil (f i r m o))
("fiscal" nil (f i s k a l))
("flanquear" nil (f l a n k e a r))
("flores" nil (f l o r e s))
("flujo" nil (f l u j o))
("focal" nil (f o k a l))
("fondo" nil (f o n d o))
("forma" nil (f o r m a))
("formación" nil (f o r m a th i o n))
("formada" nil (f o r m a d a))
("forman" nil (f o r m a n))
("formas" nil (f o r m a s))
("frente" nil (f r e n t e))
("fresa" nil (f r e s a))
("fresco" nil (f r e s k o))
("frío" nil (f r i o))
("fue" nil (f u e))
("fueron" nil (f u e r o n))
("fuerte" nil (f u e r t e))
("fuertes" nil (f u e r t e s))
("fuerzas" nil (f u e r th a s))
("fui" nil (f u i))
("funciona" nil (f u n th i o n a))
("funcionario" nil (f u n th i o n a r i o))
("funcionarán" nil (f u n th i o n a r a n))
("funeral" nil (f u n e r a l))
("futbol" nil (f u t b o l))
("fáciles" nil (f a th i l e s))
("física" nil (f i s i k a))
("físicamente" nil (f i s i k a m e n t e))
("fórmula" nil (f o r m u l a))
("fútbol" nil (f u t b o l))
("gala" nil (g a l a))
("ganaderos" nil (g a n a d e r o s))
("ganado" nil (g a n a d o))
("ganador" nil (g a n a d o r))
("ganando" nil (g a n a n d o))
("ganar" nil (g a n a r))
("garantizar" nil (g a r a n t i th a r))
("gases" nil (g a s e s))
("gasolina" nil (g a s o l i n a))
("gemelos" nil (j e m e l o s))
("general" nil (j e n e r a l))
("gente" nil (j e n t e))
("gentes" nil (j e n t e s))
("germana" nil (j e r m a n a))
("globalización" nil (g l o b a l i th a th i o n))
("gobierno" nil (g o b i e r n o))
("gobiernos" nil (g o b i e r n o s))
("gol" nil (g o l))
("goleador" nil (g o l e a d o r))
("golpe" nil (g o l p e))
("golpearlo" nil (g o l p e a r l o))
("gracias" nil (g r a th i a s))
("grados" nil (g r a d o s))
("gran" nil (g r a n))
("granadas" nil (g r a n a d a s))
("grave" nil (g r a v e))
("gravedad" nil (g r a v e d a d))
("greigo" nil (g r e i g o))
("grilletes" nil (g r i ll e t e s))
("grupo" nil (g r u p o))
("guard" nil (g u a r d))
("guardó" nil (g u a r d o))
("gubernamental" nil (g u b e r n a m e n t a l))
("guerra" nil (g e rr a))
("guitarra" nil (g i t a rr a))
("gustaría" nil (g u s t a r i a))
("ha" nil (a))
("haber" nil (a b e r))
("haberme" nil (a b e r m e))
("habilitó" nil (a b i l i t o))
("habitantes" nil (a b i t a n t e s))
("hablaba" nil (a b l a b a))
("hablar" nil (a b l a r))
("habrá" nil (a b r a))
("había" nil (a b i a))
("habían" nil (a b i a n))
("hace" nil (a th e))
("hacer" nil (a th e r))
("hacerlo" nil (a th e r l o))
("hacia" nil (a th i a))
("hagamos" nil (a g a m o s))
("hallaba" nil (a ll a b a))
("hallan" nil (a ll a n))
("hambre" nil (a m b r e))
("han" nil (a n))
("hardware" nil (a r d u a r e))
("has" nil (a s))
("hasta" nil (a s t a))
("hay" nil (a i))
("haya" nil (a y a))
("he" nil (e))
("hechas" nil (e ch a s))
("hemos" nil (e m o s))
("herida" nil (e r i d a))
("heridas" nil (e r i d a s))
("herido" nil (e r i d o))
("heridos" nil (e r i d o s))
("herrramientas" nil (e rr r a m i e n t a s))
("hidroeléctricas" nil (i d r o e l e k t r i k a s))
("hierba" nil (i e r b a))
("hijo" nil (i j o))
("hijos" nil (i j o s))
("hit" nil (i t))
("hizo" nil (i th o))
("hobby" nil (o b b i))
("holding" nil (o l d i n g))
("hombres" nil (o m b r e s))
("horas" nil (o r a s))
("hostigado" nil (o s t i g a d o))
("hoy" nil (o i))
("hubieran" nil (u b i e r a n))
("hubo" nil (u b o))
("huelga" nil (u e l g a))
("hueso" nil (u e s o))
("huesos" nil (u e s o s))
("humanitario" nil (u m a n i t a r i o))
("humedad" nil (u m e d a d))
("humo" nil (u m o))
("hundido" nil (u n d i d o))
("iba" nil (i b a))
("idea" nil (i d e a))
("ideal" nil (i d e a l))
("ido" nil (i d o))
("ignoraba" nil (i g n o r a b a))
("igualar" nil (i g u a l a r))
("igualmente" nil (i g u a l m e n t e))
("iluminar" nil (i l u m i n a r))
("iluminó" nil (i l u m i n o))
("imaginación" nil (i m a j i n a th i o n))
("impacto" nil (i m p a k t o))
("implicito" nil (i m p l i th i t o))
("importante" nil (i m p o r t a n t e))
("impulsado" nil (i m p u l s a d o))
("impuso" nil (i m p u s o))
("imputaciones" nil (i m p u t a th i o n e s))
("inaugura" nil (i n a u g u r a))
("incautaciones" nil (i n k a u t a th i o n e s))
("inclusive" nil (i n k l u s i v e))
("incluso" nil (i n k l u s o))
("incluye" nil (i n k l u y e))
("incluyen" nil (i n k l u y e n))
("inconformidad" nil (i n k o n f o r m i d a d))
("increiblemente" nil (i n k r e i b l e m e n t e))
("incrementarlas" nil (i n k r e m e n t a r l a s))
("incrementen" nil (i n k r e m e n t e n))
("incursionado" nil (i n k u r s i o n a d o))
("indico" nil (i n d i k o))
("indicó" nil (i n d i k o))
("indignado" nil (i n d i g n a d o))
("individuos" nil (i n d i v i d u o s))
("industrializado" nil (i n d u s t r i a l i th a d o))
("ineficaces" nil (i n e f i k a th e s))
("inexistentes" nil (i n e k s i s t e n t e s))
("infantes" nil (i n f a n t e s))
("infantil" nil (i n f a n t i l))
("inflamación" nil (i n f l a m a th i o n))
("influencia" nil (i n f l u e n th i a))
("informativa" nil (i n f o r m a t i v a))
("informe" nil (i n f o r m e))
("infraestructura" nil (i n f r a e s t r u k t u r a))
("ingenieros" nil (i n j e n i e r o s))
("inicial" nil (i n i th i a l))
("inmigración" nil (i n m i g r a th i o n))
("innecesarias" nil (i n n e th e s a r i a s))
("inning" nil (i n n i n g))
("inscribirse" nil (i n s k r i b i r s e))
("insistió" nil (i n s i s t i o))
("insoluble" nil (i n s o l u b l e))
("instalaciones" nil (i n s t a l a th i o n e s))
("instancia" nil (i n s t a n th i a))
("institución" nil (i n s t i t u th i o n))
("insurgencia" nil (i n s u r j e n th i a))
("integrista" nil (i n t e g r i s t a))
("intención" nil (i n t e n th i o n))
("intensamente" nil (i n t e n s a m e n t e))
("intensidad" nil (i n t e n s i d a d))
("intensos" nil (i n t e n s o s))
("intermedio" nil (i n t e r m e d i o))
("interoceánico" nil (i n t e r o th e a n i k o))
("interpretará" nil (i n t e r p r e t a r a))
("interrogatorio" nil (i n t e rr o g a t o r i o))
("intestino" nil (i n t e s t i n o))
("introducir" nil (i n t r o d u th i r))
("inventado" nil (i n v e n t a d o))
("inversiones" nil (i n v e r s i o n e s))
("investigaciones" nil (i n v e s t i g a th i o n e s))
("investigación" nil (i n v e s t i g a th i o n))
("invirtió" nil (i n v i r t i o))
("invitación" nil (i n v i t a th i o n))
("invitada" nil (i n v i t a d a))
("invitado" nil (i n v i t a d o))
("involucramiento" nil (i n v o l u k r a m i e n t o))
("inútiles" nil (i n u t i l e s))
("iranias" nil (i r a n i a s))
("iraní" nil (i r a n i))
("iraquíes" nil (i r a k i e s))
("irreversible" nil (i rr e v e r s i b l e))
("islámico" nil (i s l a m i k o))
("israelíes" nil (i s rr a e l i e s))
("it" nil (i t))
("italiano" nil (i t a l i a n o))
("jack" nil (j a k k))
("japones" nil (j a p o n e s))
("japonés" nil (j a p o n e s))
("jefe" nil (j e f e))
("jornada" nil (j o r n a d a))
("joven" nil (j o v e n))
("joyas" nil (j o y a s))
("judicial" nil (j u d i th i a l))
("juega" nil (j u e g a))
("juego" nil (j u e g o))
("juez" nil (j u e th))
("jugado" nil (j u g a d o))
("jugadores" nil (j u g a d o r e s))
("jugó" nil (j u g o))
("julio" nil (j u l i o))
("justa" nil (j u s t a))
("justifica" nil (j u s t i f i k a))
("juventud" nil (j u v e n t u d))
("kilos" nil (k i l o s))
("kilómetros" nil (k i l o m e t r o s))
("kiwi" nil (k i u i))
("km" nil (k m))
("kuwaití" nil (k u u a i t i))
("la" nil (l a))
("laminadora" nil (l a m i n a d o r a))
("lanzará" nil (l a n th a r a))
("lanzó" nil (l a n th o))
("lapidarios" nil (l a p i d a r i o s))
("largo" nil (l a r g o))
("las" nil (l a s))
("laser" nil (l a s e r))
("latinoamericano" nil (l a t i n o a m e r i k a n o))
("lavanderías" nil (l a v a n d e r i a s))
("le" nil (l e))
("lechera" nil (l e ch e r a))
("leer" nil (l e e r))
("legisladora" nil (l e j i s l a d o r a))
("lejos" nil (l e j o s))
("lenguas" nil (l e n g u a s))
("lenta" nil (l e n t a))
("lento" nil (l e n t o))
("les" nil (l e s))
("lesión" nil (l e s i o n))
("leucemia" nil (l e u th e m i a))
("ley" nil (l e i))
("leía" nil (l e i a))
("lianas" nil (l i a n a s))
("liberado" nil (l i b e r a d o))
("libertad" nil (l i b e r t a d))
("librando" nil (l i b r a n d o))
("libre" nil (l i b r e))
("licencia" nil (l i th e n th i a))
("lista" nil (l i s t a))
("litros" nil (l i t r o s))
("llamado" nil (ll a m a d o))
("llaman" nil (ll a m a n))
("llamar" nil (ll a m a r))
("llaneros" nil (ll a n e r o s))
("llanos" nil (ll a n o s))
("llega" nil (ll e g a))
("llegado" nil (ll e g a d o))
("llegando" nil (ll e g a n d o))
("llegar" nil (ll e g a r))
("llegaron" nil (ll e g a r o n))
("llegó" nil (ll e g o))
("llena" nil (ll e n a))
("llenado" nil (ll e n a d o))
("llenarlas" nil (ll e n a r l a s))
("llevando" nil (ll e v a n d o))
("llevar" nil (ll e v a r))
("llevaron" nil (ll e v a r o n))
("llevará" nil (ll e v a r a))
("llevó" nil (ll e v o))
("llora" nil (ll o r a))
("llorando" nil (ll o r a n d o))
("llorosa" nil (ll o r o s a))
("llueva" nil (ll u e v a))
("llueven" nil (ll u e v e n))
("lluvias" nil (ll u v i a s))
("lluvioso" nil (ll u v i o s o))
("lo" nil (l o))
("local" nil (l o k a l))
("logramos" nil (l o g r a m o s))
("lograron" nil (l o g r a r o n))
("logros" nil (l o g r o s))
("los" nil (l o s))
("lote" nil (l o t e))
("luce" nil (l u th e))
("luciendo" nil (l u th i e n d o))
("luego" nil (l u e g o))
("lugar" nil (l u g a r))
("lunes" nil (l u n e s))
("luz" nil (l u th))
("lámparas" nil (l a m p a r a s))
("líder" nil (l i d e r))
("líderes" nil (l i d e r e s))
("línea" nil (l i n e a))
("lógica" nil (l o j i k a))
("macizo" nil (m a th i th o))
("madurar" nil (m a d u r a r))
("magallaneras" nil (m a g a ll a n e r a s))
("magistrado" nil (m a j i s t r a d o))
("magistrales" nil (m a j i s t r a l e s))
("magma" nil (m a g m a))
("mago" nil (m a g o))
("mal" nil (m a l))
("maltrato" nil (m a l t r a t o))
("manchas" nil (m a n ch a s))
("mandarina" nil (m a n d a r i n a))
("mando" nil (m a n d o))
("maneja" nil (m a n e j a))
("manejable" nil (m a n e j a b l e))
("manejar" nil (m a n e j a r))
("manera" nil (m a n e r a))
("mango" nil (m a n g o))
("manifestado" nil (m a n i f e s t a d o))
("manifiesta" nil (m a n i f i e s t a))
("manipulada" nil (m a n i p u l a d a))
("manos" nil (m a n o s))
("mantener" nil (m a n t e n e r))
("mantiene" nil (m a n t i e n e))
("mantén" nil (m a n t e n))
("maquilador" nil (m a k i l a d o r))
("marcador" nil (m a r k a d o r))
("marcha" nil (m a r ch a))
("marcó" nil (m a r k o))
("marketing" nil (m a r k e t i n g))
("martes" nil (m a r t e s))
("matador" nil (m a t a d o r))
("match" nil (m a t ch))
("matemático" nil (m a t e m a t i k o))
("maya" nil (m a y a))
("mayor" nil (m a y o r))
("mayores" nil (m a y o r e s))
("mañana" nil (m a ny a n a))
("me" nil (m e))
("medio" nil (m e d i o))
("medios" nil (m e d i o s))
("meditado" nil (m e d i t a d o))
("mejor" nil (m e j o r))
("mejores" nil (m e j o r e s))
("melón" nil (m e l o n))
("mencionó" nil (m e n th i o n o))
("menor" nil (m e n o r))
("menos" nil (m e n o s))
("mercado" nil (m e r k a d o))
("mero" nil (m e r o))
("mes" nil (m e s))
("mesa" nil (m e s a))
("mesas" nil (m e s a s))
("meses" nil (m e s e s))
("meticulosamente" nil (m e t i k u l o s a m e n t e))
("metilterbutileter" nil (m e t i l t e r b u t i l e t e r))
("metros" nil (m e t r o s))
("mexicana" nil (m e k s i k a n a))
("mg" nil (m g))
("mi" nil (m i))
("microprocesadores" nil (m i k r o p r o th e s a d o r e s))
("mide" nil (m i d e))
("miembros" nil (m i e m b r o s))
("mil" nil (m i l))
("militar" nil (m i l i t a r))
("millones" nil (m i ll o n e s))
("minisubmarinos" nil (m i n i s u b m a r i n o s))
("minutos" nil (m i n u t o s))
("mis" nil (m i s))
("misiles" nil (m i s i l e s))
("misma" nil (m i s m a))
("mismo" nil (m i s m o))
("misteriosamente" nil (m i s t e r i o s a m e n t e))
("mitad" nil (m i t a d))
("miércoles" nil (m i e r k o l e s))
("mm" nil (m m))
("moderadamente" nil (m o d e r a d a m e n t e))
("modernos" nil (m o d e r n o s))
("mole" nil (m o l e))
("momento" nil (m o m e n t o))
("momentáneamente" nil (m o m e n t a n e a m e n t e))
("monitores" nil (m o n i t o r e s))
("monopolizados" nil (m o n o p o l i th a d o s))
("montar" nil (m o n t a r))
("monto" nil (m o n t o))
("mostraron" nil (m o s t r a r o n))
("mostró" nil (m o s t r o))
("motivación" nil (m o t i v a th i o n))
("motor" nil (m o t o r))
("movimiento" nil (m o v i m i e n t o))
("muchacha" nil (m u ch a ch a))
("muchas" nil (m u ch a s))
("mucho" nil (m u ch o))
("muerte" nil (m u e r t e))
("mujer" nil (m u j e r))
("mujeres" nil (m u j e r e s))
("mundial" nil (m u n d i a l))
("mundo" nil (m u n d o))
("muy" nil (m u i))
("máquinas" nil (m a k i n a s))
("más" nil (m a s))
("mí" nil (m i))
("mínima" nil (m i n i m a))
("mío" nil (m i o))
("mítines" nil (m i t i n e s))
("música" nil (m u s i k a))
("músicos" nil (m u s i k o s))
("nacional" nil (n a th i o n a l))
("nació" nil (n a th i o))
("nada" nil (n a d a))
("naranja" nil (n a r a n j a))
("narcotráfico" nil (n a r k o t r a f i k o))
("naufragio" nil (n a u f r a j i o))
("necesaria" nil (n e th e s a r i a))
("necesario" nil (n e th e s a r i o))
("negar" nil (n e g a r))
("negociaciones" nil (n e g o th i a th i o n e s))
("negociadores" nil (n e g o th i a d o r e s))
("negociar" nil (n e g o th i a r))
("negocio" nil (n e g o th i o))
("negociosdespegar" nil (n e g o th i o s d e s p e g a r))
("negra" nil (n e g r a))
("negro" nil (n e g r o))
("ni" nil (n i))
("nido" nil (n i d o))
("niega" nil (n i e g a))
("ninguna" nil (n i n g u n a))
("ningunar" nil (n i n g u n a r))
("ningún" nil (n i n g u n))
("nivel" nil (n i v e l))
("niña" nil (n i ny a))
("niñerías" nil (n i ny e r i a s))
("niño" nil (n i ny o))
("niños" nil (n i ny o s))
("no" nil (n o))
("noche" nil (n o ch e))
("nocivo" nil (n o th i v o))
("nombrado" nil (n o m b r a d o))
("nombrados" nil (n o m b r a d o s))
("nombramientos" nil (n o m b r a m i e n t o s))
("nombres" nil (n o m b r e s))
("nominadas" nil (n o m i n a d a s))
("noroeste" nil (n o r o e s t e))
("norteamericano" nil (n o r t e a m e r i k a n o))
("nos" nil (n o s))
("nosotros" nil (n o s o t r o s))
("novecientos" nil (n o v e th i e n t o s))
("noventa" nil (n o v e n t a))
("noventai" nil (n o v e n t a i))
("nublado" nil (n u b l a d o))
("nucleares" nil (n u k l e a r e s))
("nuestra" nil (n u e s t r a))
("nuestro" nil (n u e s t r o))
("nueva" nil (n u e v a))
("nuevamente" nil (n u e v a m e n t e))
("nueve" nil (n u e v e))
("nuevo" nil (n u e v o))
("nuevos" nil (n u e v o s))
("nuez" nil (n u e th))
("nunca" nil (n u n k a))
("número" nil (n u m e r o))
("objeto" nil (o b j e t o))
("obra" nil (o b r a))
("obstante" nil (o b s t a n t e))
("obtendrá" nil (o b t e n d r a))
("obtener" nil (o b t e n e r))
("obtuvo" nil (o b t u v o))
("obuses" nil (o b u s e s))
("ocasiones" nil (o k a s i o n e s))
("ocasión" nil (o k a s i o n))
("occidental" nil (o k th i d e n t a l))
("occidentales" nil (o k th i d e n t a l e s))
("ochentai" nil (o ch e n t a i))
("ocho" nil (o ch o))
("octubre" nil (o k t u b r e))
("ocurre" nil (o k u rr e))
("ocurrió" nil (o k u rr i o))
("océanos" nil (o th e a n o s))
("oeste" nil (o e s t e))
("oficial" nil (o f i th i a l))
("oficiales" nil (o f i th i a l e s))
("oficializaron" nil (o f i th i a l i th a r o n))
("oficialmente" nil (o f i th i a l m e n t e))
("ofrece" nil (o f r e th e))
("ofrecieran" nil (o f r e th i e r a n))
("ojos" nil (o j o s))
("olvida" nil (o l v i d a))
("olvidado" nil (o l v i d a d o))
("olímpico" nil (o l i m p i k o))
("once" nil (o n th e))
("opciones" nil (o p th i o n e s))
("operación" nil (o p e r a th i o n))
("operativo" nil (o p e r a t i v o))
("opinión" nil (o p i n i o n))
("oportunidad" nil (o p o r t u n i d a d))
("oposición" nil (o p o s i th i o n))
("organismo" nil (o r g a n i s m o))
("organismos" nil (o r g a n i s m o s))
("organización" nil (o r g a n i th a th i o n))
("organizado" nil (o r g a n i th a d o))
("orgulloso" nil (o r g u ll o s o))
("origen" nil (o r i j e n))
("originalmente" nil (o r i j i n a l m e n t e))
("orquesta" nil (o r k e s t a))
("otoño" nil (o t o ny o))
("otra" nil (o t r a))
("otras" nil (o t r a s))
("otro" nil (o t r o))
("otros" nil (o t r o s))
("paciencia" nil (p a th i e n th i a))
("padece" nil (p a d e th e))
("padre" nil (p a d r e))
("pagado" nil (p a g a d o))
("pagar" nil (p a g a r))
("pagos" nil (p a g o s))
("paises" nil (p a i s e s))
("palabras" nil (p a l a b r a s))
("palmas" nil (p a l m a s))
("palmeirense" nil (p a l m e i r e n s e))
("panamericanos" nil (p a n a m e r i k a n o s))
("pandilleros" nil (p a n d i ll e r o s))
("papaya" nil (p a p a y a))
("papás" nil (p a p a s))
("para" nil (p a r a))
("paraje" nil (p a r a j e))
("paralelas" nil (p a r a l e l a s))
("paralítico" nil (p a r a l i t i k o))
("parece" nil (p a r e th e))
("parecen" nil (p a r e th e n))
("parlamentario" nil (p a r l a m e n t a r i o))
("parlamentarios" nil (p a r l a m e n t a r i o s))
("paro" nil (p a r o))
("parsimonio" nil (p a r s i m o n i o))
("parte" nil (p a r t e))
("partes" nil (p a r t e s))
("participación" nil (p a r t i th i p a th i o n))
("participantes" nil (p a r t i th i p a n t e s))
("participar" nil (p a r t i th i p a r))
("participativos" nil (p a r t i th i p a t i v o s))
("particular" nil (p a r t i k u l a r))
("partido" nil (p a r t i d o))
("partir" nil (p a r t i r))
("pasa" nil (p a s a))
("pasado" nil (p a s a d o))
("pasar" nil (p a s a r))
("pasión" nil (p a s i o n))
("paso" nil (p a s o))
("patria" nil (p a t r i a))
("patrulla" nil (p a t r u ll a))
("pavo" nil (p a v o))
("país" nil (p a i s))
("países" nil (p a i s e s))
("pedido" nil (p e d i d o))
("peligrosa" nil (p e l i g r o s a))
("pelotón" nil (p e l o t o n))
("penal" nil (p e n a l))
("penales" nil (p e n a l e s))
("penas" nil (p e n a s))
("pensamos" nil (p e n s a m o s))
("peor" nil (p e o r))
("pequeños" nil (p e k e ny o s))
("perdió" nil (p e r d i o))
("perfección" nil (p e r f e k th i o n))
("perfectamente" nil (p e r f e k t a m e n t e))
("permisionarios" nil (p e r m i s i o n a r i o s))
("permita" nil (p e r m i t a))
("permite" nil (p e r m i t e))
("pero" nil (p e r o))
("personal" nil (p e r s o n a l))
("pertenecen" nil (p e r t e n e th e n))
("pesado" nil (p e s a d o))
("pianistas" nil (p i a n i s t a s))
("pidió" nil (p i d i o))
("piernas" nil (p i e r n a s))
("pista" nil (p i s t a))
("pistolas" nil (p i s t o l a s))
("pitcheo" nil (p i t ch e o))
("plagiarios" nil (p l a j i a r i o s))
("planes" nil (p l a n e s))
("planeta" nil (p l a n e t a))
("planta" nil (p l a n t a))
("playoffs" nil (p l a y o f f s))
("plazo" nil (p l a th o))
("plomo" nil (p l o m o))
("plutonio" nil (p l u t o n i o))
("poblano" nil (p o b l a n o))
("pobre" nil (p o b r e))
("poco" nil (p o k o))
("pocos" nil (p o k o s))
("poder" nil (p o d e r))
("podido" nil (p o d i d o))
("podrán" nil (p o d r a n))
("podría" nil (p o d r i a))
("podrían" nil (p o d r i a n))
("poetisa" nil (p o e t i s a))
("policial" nil (p o l i th i a l))
("policlínico" nil (p o l i k l i n i k o))
("policía" nil (p o l i th i a))
("policías" nil (p o l i th i a s))
("politiquería" nil (p o l i t i k e r i a))
("política" nil (p o l i t i k a))
("políticos" nil (p o l i t i k o s))
("ponchó" nil (p o n ch o))
("pontífice" nil (p o n t i f i th e))
("popular" nil (p o p u l a r))
("poquito" nil (p o k i t o))
("por" nil (p o r))
("porque" nil (p o r k e))
("portavoz" nil (p o r t a v o th))
("portero" nil (p o r t e r o))
("portuaria" nil (p o r t u a r i a))
("posición" nil (p o s i th i o n))
("positiva" nil (p o s i t i v a))
("positivo" nil (p o s i t i v o))
("potencia" nil (p o t e n th i a))
("potencial" nil (p o t e n th i a l))
("potente" nil (p o t e n t e))
("pozos" nil (p o th o s))
("preaviso" nil (p r e a v i s o))
("precios" nil (p r e th i o s))
("precisaba" nil (p r e th i s a b a))
("precisado" nil (p r e th i s a d o))
("precisiones" nil (p r e th i s i o n e s))
("precisó" nil (p r e th i s o))
("preguntaba" nil (p r e g u n t a b a))
("preliminares" nil (p r e l i m i n a r e s))
("preludio" nil (p r e l u d i o))
("premio" nil (p r e m i o))
("premios" nil (p r e m i o s))
("prendas" nil (p r e n d a s))
("prensa" nil (p r e n s a))
("preocupaciones" nil (p r e o k u p a th i o n e s))
("preocupación" nil (p r e o k u p a th i o n))
("preocupante" nil (p r e o k u p a n t e))
("preparados" nil (p r e p a r a d o s))
("preparan" nil (p r e p a r a n))
("preparando" nil (p r e p a r a n d o))
("preparas" nil (p r e p a r a s))
("presentado" nil (p r e s e n t a d o))
("presentan" nil (p r e s e n t a n))
("presente" nil (p r e s e n t e))
("presenten" nil (p r e s e n t e n))
("presidencial" nil (p r e s i d e n th i a l))
("presidente" nil (p r e s i d e n t e))
("presos" nil (p r e s o s))
("prestar" nil (p r e s t a r))
("presunto" nil (p r e s u n t o))
("primas" nil (p r i m a s))
("primer" nil (p r i m e r))
("primera" nil (p r i m e r a))
("primeras" nil (p r i m e r a s))
("primero" nil (p r i m e r o))
("primeros" nil (p r i m e r o s))
("princesa" nil (p r i n th e s a))
("principal" nil (p r i n th i p a l))
("principio" nil (p r i n th i p i o))
("principios" nil (p r i n th i p i o s))
("privados" nil (p r i v a d o s))
("privatización" nil (p r i v a t i th a th i o n))
("problema" nil (p r o b l e m a))
("problemas" nil (p r o b l e m a s))
("procesador" nil (p r o th e s a d o r))
("proceso" nil (p r o th e s o))
("producción" nil (p r o d u k th i o n))
("producidos" nil (p r o d u th i d o s))
("productivos" nil (p r o d u k t i v o s))
("producto" nil (p r o d u k t o))
("produjo" nil (p r o d u j o))
("profesional" nil (p r o f e s i o n a l))
("profundidad" nil (p r o f u n d i d a d))
("programa" nil (p r o g r a m a))
("programas" nil (p r o g r a m a s))
("progresivamente" nil (p r o g r e s i v a m e n t e))
("pronósticos" nil (p r o n o s t i k o s))
("propaganda" nil (p r o p a g a n d a))
("propiedad" nil (p r o p i e d a d))
("propio" nil (p r o p i o))
("propuesta" nil (p r o p u e s t a))
("propósitos" nil (p r o p o s i t o s))
("prosigue" nil (p r o s i g e))
("protagonismo" nil (p r o t a g o n i s m o))
("protegidas" nil (p r o t e j i d a s))
("proyecto" nil (p r o y e k t o))
("prueba" nil (p r u e b a))
("próximo" nil (p r o k s i m o))
("pudieron" nil (p u d i e r o n))
("pudo" nil (p u d o))
("pueblo" nil (p u e b l o))
("puede" nil (p u e d e))
("pueden" nil (p u e d e n))
("puedes" nil (p u e d e s))
("puertorriqueño" nil (p u e r t o rr i k e ny o))
("pues" nil (p u e s))
("pugnas" nil (p u g n a s))
("punto" nil (p u n t o))
("puntualidad" nil (p u n t u a l i d a d))
("pura" nil (p u r a))
("pusimos" nil (p u s i m o s))
("pálido" nil (p a l i d o))
("pérdidas" nil (p e r d i d a s))
("pública" nil (p u b l i k a))
("público" nil (p u b l i k o))
("públicos" nil (p u b l i k o s))
("que" nil (k e))
("quechua" nil (k e ch u a))
("quedan" nil (k e d a n))
("quedando" nil (k e d a n d o))
("quedaron" nil (k e d a r o n))
("quedará" nil (k e d a r a))
("quedó" nil (k e d o))
("querellaré" nil (k e r e ll a r e))
("quien" nil (k i e n))
("quienes" nil (k i e n e s))
("quiera" nil (k i e r a))
("quiere" nil (k i e r e))
("quieres" nil (k i e r e s))
("quince" nil (k i n th e))
("quinientos" nil (k i n i e n t o s))
("quiso" nil (k i s o))
("quitaron" nil (k i t a r o n))
("quitándolos" nil (k i t a n d o l o s))
("quizás" nil (k i th a s))
("qué" nil (k e))
("químico" nil (k i m i k o))
("radio" nil (rr a d i o))
("raro" nil (rr a r o))
("ratificados" nil (rr a t i f i k a d o s))
("ratificar" nil (rr a t i f i k a r))
("ratones" nil (rr a t o n e s))
("ratón" nil (rr a t o n))
("rayanas" nil (rr a y a n a s))
("rayitos" nil (rr a y i t o s))
("razones" nil (rr a th o n e s))
("raíz" nil (rr a i th))
("real" nil (rr e a l))
("realidad" nil (rr e a l i d a d))
("rebeldes" nil (rr e b e l d e s))
("recalcó" nil (rr e k a l k o))
("recesiones" nil (rr e th e s i o n e s))
("rechazadas" nil (rr e ch a th a d a s))
("rechazados" nil (rr e ch a th a d o s))
("rechazó" nil (rr e ch a th o))
("recibe" nil (rr e th i b e))
("recibiendo" nil (rr e th i b i e n d o))
("recibiera" nil (rr e th i b i e r a))
("recibir" nil (rr e th i b i r))
("recomendaciones" nil (rr e k o m e n d a th i o n e s))
("recomendada" nil (rr e k o m e n d a d a))
("reconstrucción" nil (rr e k o n s t r u k th i o n))
("records" nil (rr e k o r d s))
("recordó" nil (rr e k o r d o))
("rector" nil (rr e k t o r))
("recuperaba" nil (rr e k u p e r a b a))
("recursos" nil (rr e k u r s o s))
("reducción" nil (rr e d u k th i o n))
("reduce" nil (rr e d u th e))
("reducir" nil (rr e d u th i r))
("reemplazados" nil (rr e e m p l a th a d o s))
("referirse" nil (rr e f e r i r s e))
("refiriéndose" nil (rr e f i r i e n d o s e))
("refuerzos" nil (rr e f u e r th o s))
("regiomontana" nil (rr e j i o m o n t a n a))
("regionales" nil (rr e j i o n a l e s))
("registraron" nil (rr e j i s t r a r o n))
("reglas" nil (rr e g l a s))
("regular" nil (rr e g u l a r))
("rehusó" nil (rr e u s o))
("reinó" nil (rr e i n o))
("reivindica" nil (rr e i v i n d i k a))
("reivindicado" nil (rr e i v i n d i k a d o))
("reivindicó" nil (rr e i v i n d i k o))
("relación" nil (rr e l a th i o n))
("relativa" nil (rr e l a t i v a))
("relativamente" nil (rr e l a t i v a m e n t e))
("relató" nil (rr e l a t o))
("relegado" nil (rr e l e g a d o))
("religioso" nil (rr e l i j i o s o))
("reloj" nil (rr e l o j))
("relojes" nil (rr e l o j e s))
("rensañamiento" nil (rr e n s a ny a m i e n t o))
("rentable" nil (rr e n t a b l e))
("repelente" nil (rr e p e l e n t e))
("repetar" nil (rr e p e t a r))
("repitiéndome" nil (rr e p i t i e n d o m e))
("reportero" nil (rr e p o r t e r o))
("representa" nil (rr e p r e s e n t a))
("requiere" nil (rr e k i e r e))
("reserva" nil (rr e s e r v a))
("resistentes" nil (rr e s i s t e n t e s))
("resistir" nil (rr e s i s t i r))
("resolucion" nil (rr e s o l u th i o n))
("resolver" nil (rr e s o l v e r))
("resolverlo" nil (rr e s o l v e r l o))
("respecto" nil (rr e s p e k t o))
("respeta" nil (rr e s p e t a))
("responsabilidad" nil (rr e s p o n s a b i l i d a d))
("responsable" nil (rr e s p o n s a b l e))
("responsables" nil (rr e s p o n s a b l e s))
("respuesta" nil (rr e s p u e s t a))
("resueltos" nil (rr e s u e l t o s))
("resultado" nil (rr e s u l t a d o))
("resultados" nil (rr e s u l t a d o s))
("resulto" nil (rr e s u l t o))
("retirar" nil (rr e t i r a r))
("retiro" nil (rr e t i r o))
("retornar" nil (rr e t o r n a r))
("retrasar" nil (rr e t r a s a r))
("retrospectivas" nil (rr e t r o s p e k t i v a s))
("reubicados" nil (rr e u b i k a d o s))
("reunirse" nil (rr e u n i r s e))
("reunión" nil (rr e u n i o n))
("reyertas" nil (rr e y e r t a s))
("riesgo" nil (rr i e s g o))
("rinde" nil (rr i n d e))
("ritmo" nil (rr i t m o))
("rival" nil (rr i v a l))
("rivales" nil (rr i v a l e s))
("robados" nil (rr o b a d o s))
("rocoso" nil (rr o k o s o))
("roer" nil (rr o e r))
("rojos" nil (rr o j o s))
("romano" nil (rr o m a n o))
("ronda" nil (rr o n d a))
("rugby" nil (rr u g b i))
("rumano" nil (rr u m a n o))
("ruso" nil (rr u s o))
("rusos" nil (rr u s o s))
("ríe" nil (rr i e))
("sabe" nil (s a b e))
("sabemos" nil (s a b e m o s))
("saber" nil (s a b e r))
("sacado" nil (s a k a d o))
("sacrificio" nil (s a k r i f i th i o))
("saldo" nil (s a l d o))
("sale" nil (s a l e))
("saliente" nil (s a l i e n t e))
("salvó" nil (s a l v o))
("sandwich" nil (s a n d u i ch))
("sandía" nil (s a n d i a))
("santuario" nil (s a n t u a r i o))
("scoth" nil (s k o t))
("se" nil (s e))
("sean" nil (s e a n))
("secesión" nil (s e th e s i o n))
("sectores" nil (s e k t o r e s))
("seda" nil (s e d a))
("seg" nil (s e g))
("seguirá" nil (s e g i r a))
("segunda" nil (s e g u n d a))
("segundo" nil (s e g u n d o))
("seguridad" nil (s e g u r i d a d))
("seguro" nil (s e g u r o))
("según" nil (s e g u n))
("seis" nil (s e i s))
("seleccionado" nil (s e l e k th i o n a d o))
("semanario" nil (s e m a n a r i o))
("semanas" nil (s e m a n a s))
("semejante" nil (s e m e j a n t e))
("senderos" nil (s e n d e r o s))
("sentenció" nil (s e n t e n th i o))
("sentido" nil (s e n t i d o))
("ser" nil (s e r))
("serbio" nil (s e r b i o))
("seremos" nil (s e r e m o s))
("series" nil (s e r i e s))
("serios" nil (s e r i o s))
("servicio" nil (s e r v i th i o))
("servicios" nil (s e r v i th i o s))
("servir" nil (s e r v i r))
("será" nil (s e r a))
("sería" nil (s e r i a))
("sesenta" nil (s e s e n t a))
("sesentai" nil (s e s e n t a i))
("setenta" nil (s e t e n t a))
("setentai" nil (s e t e n t a i))
("sexto" nil (s e s t o))
("sexual" nil (s e k s u a l))
("sexualmente" nil (s e k s u a l m e n t e))
("señala" nil (s e ny a l a))
("señaló" nil (s e ny a l o))
("señor" nil (s e ny o r))
("shorts" nil (s o r t s))
("si" nil (s i))
("siberiana" nil (s i b e r i a n a))
("sido" nil (s i d o))
("siempre" nil (s i e m p r e))
("siente" nil (s i e n t e))
("siete" nil (s i e t e))
("siglo" nil (s i g l o))
("significa" nil (s i g n i f i k a))
("significativo" nil (s i g n i f i k a t i v o))
("sigue" nil (s i g e))
("siguiente" nil (s i g i e n t e))
("silla" nil (s i ll a))
("similar" nil (s i m i l a r))
("sin" nil (s i n))
("sindical" nil (s i n d i k a l))
("sino" nil (s i n o))
("sintiéndome" nil (s i n t i e n d o m e))
("sionista" nil (s i o n i s t a))
("siquiera" nil (s i k i e r a))
("sismo" nil (s i s m o))
("sistema" nil (s i s t e m a))
("sistemas" nil (s i s t e m a s))
("snobismo" nil (s n o b i s m o))
("soberana" nil (s o b e r a n a))
("sobornos" nil (s o b o r n o s))
("sobre" nil (s o b r e))
("sobrevive" nil (s o b r e v i v e))
("social" nil (s o th i a l))
("socialista" nil (s o th i a l i s t a))
("sociedad" nil (s o th i e d a d))
("softbol" nil (s o f t b o l))
("software" nil (s o f t u a r e))
("solamente" nil (s o l a m e n t e))
("soldados" nil (s o l d a d o s))
("solicitado" nil (s o l i th i t a d o))
("solicitar" nil (s o l i th i t a r))
("solitarios" nil (s o l i t a r i o s))
("solo" nil (s o l o))
("soluciones" nil (s o l u th i o n e s))
("son" nil (s o n))
("sonido" nil (s o n i d o))
("sorpresa" nil (s o r p r e s a))
("sospechos" nil (s o s p e ch o s))
("soviética" nil (s o v i e t i k a))
("soy" nil (s o i))
("soñadores" nil (s o ny a d o r e s))
("soñando" nil (s o ny a n d o))
("staff" nil (s t a f f))
("su" nil (s u))
("subconsciente" nil (s u b k o n s th i e n t e))
("subgrupo" nil (s u b g r u p o))
("subviertes" nil (s u b v i e r t e s))
("subyugada" nil (s u b y u g a d a))
("sucede" nil (s u th e d e))
("sucedió" nil (s u th e d i o))
("sucesión" nil (s u th e s i o n))
("suelo" nil (s u e l o))
("sufrir" nil (s u f r i r))
("sugerentes" nil (s u j e r e n t e s))
("sujeto" nil (s u j e t o))
("suposiciones" nil (s u p o s i th i o n e s))
("supuestamente" nil (s u p u e s t a m e n t e))
("suryemenitas" nil (s u r y e m e n i t a s))
("sus" nil (s u s))
("susodicho" nil (s u s o d i ch o))
("suspensión" nil (s u s p e n s i o n))
("sustancias" nil (s u s t a n th i a s))
("suyo" nil (s u y o))
("sábado" nil (s a b a d o))
("sí" nil (s i))
("símbolo" nil (s i m b o l o))
("sólo" nil (s o l o))
("tabla" nil (t a b l a))
("tachuelas" nil (t a ch u e l a s))
("taconeo" nil (t a k o n e o))
("taiga" nil (t a i g a))
("tal" nil (t a l))
("talentosos" nil (t a l e n t o s o s))
("también" nil (t a m b i e n))
("tampoco" nil (t a m p o k o))
("tan" nil (t a n))
("tanques" nil (t a n k e s))
("tanto" nil (t a n t o))
("tapar" nil (t a p a r))
("tarde" nil (t a r d e))
("tarifas" nil (t a r i f a s))
("tarjetas" nil (t a r j e t a s))
("tasa" nil (t a s a))
("taxista" nil (t a k s i s t a))
("te" nil (t e))
("teatro" nil (t e a t r o))
("tecnica" nil (t e k n i k a))
("tecnología" nil (t e k n o l o j i a))
("teddys" nil (t e d d i s))
("tejidos" nil (t e j i d o s))
("telefónicas" nil (t e l e f o n i k a s))
("telefónico" nil (t e l e f o n i k o))
("temen" nil (t e m e n))
("temporada" nil (t e m p o r a d a))
("tendencia" nil (t e n d e n th i a))
("tendrá" nil (t e n d r a))
("tenemos" nil (t e n e m o s))
("tenerla" nil (t e n e r l a))
("tenga" nil (t e n g a))
("tenían" nil (t e n i a n))
("terminar" nil (t e r m i n a r))
("terminará" nil (t e r m i n a r a))
("terreno" nil (t e rr e n o))
("territorio" nil (t e rr i t o r i o))
("terrorismo" nil (t e rr o r i s m o))
("testigos" nil (t e s t i g o s))
("texto" nil (t e s t o))
("ti" nil (t i))
("tiempo" nil (t i e m p o))
("tiendas" nil (t i e n d a s))
("tiene" nil (t i e n e))
("tienen" nil (t i e n e n))
("tipo" nil (t i p o))
("tirado" nil (t i r a d o))
("tiro" nil (t i r o))
("tiroteo" nil (t i r o t e o))
("titular" nil (t i t u l a r))
("tocarán" nil (t o k a r a n))
("tocó" nil (t o k o))
("toda" nil (t o d a))
("todas" nil (t o d a s))
("todavía" nil (t o d a v i a))
("todo" nil (t o d o))
("todos" nil (t o d o s))
("tomaba" nil (t o m a b a))
("tomaremos" nil (t o m a r e m o s))
("tome" nil (t o m e))
("torneo" nil (t o r n e o))
("toros" nil (t o r o s))
("total" nil (t o t a l))
("trabajadores" nil (t r a b a j a d o r e s))
("trabajan" nil (t r a b a j a n))
("trabajando" nil (t r a b a j a n d o))
("trabajo" nil (t r a b a j o))
("traducido" nil (t r a d u th i d o))
("trae" nil (t r a e))
("transfirió" nil (t r a n s f i r i o))
("transformaren" nil (t r a n s f o r m a r e n))
("transnacional" nil (t r a n s n a th i o n a l))
("transnacionales" nil (t r a n s n a th i o n a l e s))
("tras" nil (t r a s))
("trasplantarlos" nil (t r a s p l a n t a r l o s))
("trastornos" nil (t r a s t o r n o s))
("trata" nil (t r a t a))
("tratado" nil (t r a t a d o))
("tratará" nil (t r a t a r a))
("trece" nil (t r e th e))
("treinta" nil (t r e i n t a))
("tren" nil (t r e n))
("trentai" nil (t r e n t a i))
("tres" nil (t r e s))
("triquiñuela" nil (t r i k i ny u e l a))
("triunfo" nil (t r i u n f o))
("tuberías" nil (t u b e r i a s))
("tuerto" nil (t u e r t o))
("tuvieron" nil (t u v i e r o n))
("tí" nil (t i))
("título" nil (t i t u l o))
("tóxicas" nil (t o k s i k a s))
("tú" nil (t u))
("ultra" nil (u l t r a))
("un" nil (u n))
("una" nil (u n a))
("unas" nil (u n a s))
("undécima" nil (u n d e th i m a))
("uniformes" nil (u n i f o r m e s))
("unilateral" nil (u n i l a t e r a l))
("uno" nil (u n o))
("unos" nil (u n o s))
("uranio" nil (u r a n i o))
("urgente" nil (u r j e n t e))
("usa" nil (u s a))
("usadas" nil (u s a d a s))
("usado" nil (u s a d o))
("uso" nil (u s o))
("usted" nil (u s t e d))
("utilizan" nil (u t i l i th a n))
("utilizar" nil (u t i l i th a r))
("utilizarán" nil (u t i l i th a r a n))
("utllizar" nil (u t ll i th a r))
("va" nil (v a))
("vale" nil (v a l e))
("valor" nil (v a l o r))
("vamos" nil (v a m o s))
("van" nil (v a n))
("varias" nil (v a r i a s))
("variedad" nil (v a r i e d a d))
("varios" nil (v a r i o s))
("vasos" nil (v a s o s))
("vayamos" nil (v a y a m o s))
("veces" nil (v e th e s))
("vecina" nil (v e th i n a))
("vecinos" nil (v e th i n o s))
("vehículo" nil (v e i k u l o))
("vehículos" nil (v e i k u l o s))
("veinte" nil (v e i n t e))
("ven" nil (v e n))
("vencedor" nil (v e n th e d o r))
("vendió" nil (v e n d i o))
("venta" nil (v e n t a))
("ventaja" nil (v e n t a j a))
("venti" nil (v e n t i))
("venía" nil (v e n i a))
("ver" nil (v e r))
("verdad" nil (v e r d a d))
("verdadera" nil (v e r d a d e r a))
("versiones" nil (v e r s i o n e s))
("vestidos" nil (v e s t i d o s))
("veteranos" nil (v e t e r a n o s))
("vez" nil (v e th))
("vibradores" nil (v i b r a d o r e s))
("victoria" nil (v i k t o r i a))
("victorias" nil (v i k t o r i a s))
("vida" nil (v i d a))
("vieja" nil (v i e j a))
("viernes" nil (v i e r n e s))
("vigilantes" nil (v i j i l a n t e s))
("vigor" nil (v i g o r))
("violador" nil (v i o l a d o r))
("violencia" nil (v i o l e n th i a))
("violento" nil (v i o l e n t o))
("virgen" nil (v i r j e n))
("virtud" nil (v i r t u d))
("visibles" nil (v i s i b l e s))
("visitar" nil (v i s i t a r))
("vive" nil (v i v e))
("viviendo" nil (v i v i e n d o))
("vivimos" nil (v i v i m o s))
("vivir" nil (v i v i r))
("vivió" nil (v i v i o))
("vivíamos" nil (v i v i a m o s))
("vocal" nil (v o k a l))
("volantes" nil (v o l a n t e s))
("voltereta" nil (v o l t e r e t a))
("voluntarioso" nil (v o l u n t a r i o s o))
("votos" nil (v o t o s))
("voz" nil (v o th))
("vuelto" nil (v u e l t o))
("vuelve" nil (v u e l v e))
("vías" nil (v i a s))
("víspera" nil (v i s p e r a))
("ya" nil (y a))
("yardas" nil (y a r d a s))
("yo" nil (y o))
("yugoslava" nil (y u g o s l a v a))
("zona" nil (th o n a))
("zurdo" nil (th u r d o))
("árabes" nil (a r a b e s))
("árbol" nil (a r b o l))
("él" nil (e l))
("época" nil (e p o k a))
("ésas" nil (e s a s))
("éste" nil (e s t e))
("éxitos" nil (e k s i t o s))
("íbamos" nil (i b a m o s))
("índice" nil (i n d i th e))
("última" nil (u l t i m a))
("últimas" nil (u l t i m a s))
("último" nil (u l t i m o))
("últimos" nil (u l t i m o s))
("única" nil (u n i k a))
("únicamente" nil (u n i k a m e n t e))
("único" nil (u n i k o))
("útil" nil (u t i l))
